Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-11, with the labels that each got.

#1352 Preparing to drop Error()
  src/Engine/Engine.cpp
  src/Engine/LodTextureCache.cpp
  src/Engine/LodTextureCache.h
Labels: 🥺Ready for Review

#1353 Dropped ErrorHandling.h/cpp
  HACKING.md
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameWindowHandler.cpp
  src/Arcomage/Arcomage.cpp
  src/Bin/OpenEnroth/OpenEnroth.cpp
  src/Engine/CMakeLists.txt
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/ErrorHandling.cpp
  src/Engine/ErrorHandling.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/GameResourceManager.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/ClippingFunctions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Level/Decoration.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/Texture_MM7.cpp
  src/Engine/LodSpriteCache.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/Monsters.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Tables/ItemTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/Engine/mm7text_ru.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/NPCTopics.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UITransition.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/MediaPlayer.cpp
Labels: 🥺Ready for Review

#1358 Added keys F13-F24
  src/Io/Key.cpp
  src/Library/Platform/Interface/PlatformEnums.h
  src/Library/Platform/Sdl/SdlEnumTranslation.cpp
Labels: 🥺Ready for Review

#1359 Preparing to drop GUIWindow::wData
  src/Application/Game.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIInventory.h
  src/GUI/UI/UISpell.cpp
  src/GUI/UI/UISpell.h
  src/Io/Mouse.cpp
Labels: 🥺Ready for Review

#1360 Resolved a TODO in weapon recovery table
  src/Engine/Objects/Character.cpp
  src/Engine/mm7_data.cpp
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review

#1365 Fix saving in Arena
  src/Application/GameMenu.cpp
  src/Engine/SaveLoad.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review

#1361 Dropped GUIWindow::wData
  src/Application/Game.cpp
  src/Application/GameOver.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIDialogues.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UIBooks.h
  src/GUI/UI/UIBranchlessDialogue.cpp
  src/GUI/UI/UIBranchlessDialogue.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIChest.h
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIDialogue.h
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIGameOver.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIInventory.h
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIMessageScroll.h
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UISpell.cpp
  src/GUI/UI/UISpellbook.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/Mouse.cpp
Labels: 🥺Ready for Review

#1366 Cleaned up config handling for trace recording & playback
  src/Application/GameConfig.cpp
  src/Application/GameConfig.h
  src/Bin/OpenEnroth/OpenEnroth.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceStateAccessor.cpp
  src/Engine/Components/Trace/EngineTraceStateAccessor.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/TestController.cpp
Labels: 🥺Ready for Review

#1367 Fixes in data path resolution code
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GamePathResolver.cpp
  src/Application/GamePathResolver.h
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Library/Environment/Interface/Environment.h
  src/Utility/DataPath.cpp
  src/Utility/DataPath.h
Labels: 🥺Ready for Review

#1369 Cleanup
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Engine/Engine.cpp
  src/Engine/Objects/Character.cpp
  src/Library/Environment/Interface/Environment.h
  src/Library/Platform/Sdl/SdlEnumTranslation.h
  src/Library/Platform/Sdl/SdlEventLoop.cpp
  src/Library/Platform/Sdl/SdlGamepad.h
  src/Library/Platform/Sdl/SdlPlatform.cpp
  src/Library/Platform/Sdl/SdlPlatformSharedState.cpp
  src/Library/Platform/Sdl/SdlPlatformSharedState.h
  src/Library/Platform/Sdl/SdlWindow.cpp
  src/Library/Platform/Sdl/SdlWindow.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Audio/AudioSamplePool.cpp
  src/Media/Audio/AudioSamplePool.h
  src/Media/Audio/CMakeLists.txt
  src/Media/Audio/OpenALAudioDataSource.cpp
  src/Media/Audio/OpenALAudioDataSource.h
  src/Media/Audio/OpenALSample16.cpp
  src/Media/Audio/OpenALSample16.h
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/Audio/OpenALSoundProvider.h
  src/Media/Audio/OpenALTrack16.cpp
  src/Media/Audio/OpenALTrack16.h
  src/Media/Audio/OpenALUpdateThread.h
  src/Media/Audio/SoundInfo.h
  src/Media/Audio/SoundList.cpp
  src/Media/Audio/SoundList.h
  src/Media/AudioBaseDataSource.cpp
  src/Media/AudioBaseDataSource.h
  src/Media/AudioBufferDataSource.cpp
  src/Media/AudioBufferDataSource.h
  src/Media/AudioDataSource.h
  src/Media/AudioFileDataSource.cpp
  src/Media/AudioFileDataSource.h
  src/Media/AudioSample.h
  src/Media/AudioTrack.h
  src/Media/CMakeLists.txt
  src/Media/Media.cpp
  src/Media/Media.h
  src/Media/MediaPlayer.cpp
  src/Media/MediaPlayer.h
  src/Media/Movie.h
  src/Media/VideoDataSource.h
  src/Utility/MapAccess.h
Labels: 🥺Ready for Review

#1373 Use inplace member initialization everywhere
  src/Engine/Graphics/TextureFrameTable.h
  src/Engine/Graphics/Weather.h
  src/Engine/Tables/TileTable.h
  src/Engine/Time.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/JournalBook.h
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/QuestBook.h
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Library/Logger/Logger.cpp
  src/Library/Logger/Logger.h
  src/Media/Audio/AudioPlayer.h
  src/Media/MediaPlayer.cpp
Labels: 🥺Ready for Review

#1372 Working on audio
  src/Engine/Engine.cpp
  src/Library/CMakeLists.txt
  src/Library/Lod/CMakeLists.txt
  src/Library/Lod/LodReader.h
  src/Library/Platform/Sdl/SdlEnumTranslation.cpp
  src/Library/Snd/CMakeLists.txt
  src/Library/Snd/SndReader.cpp
  src/Library/Snd/SndReader.h
  src/Library/Snd/SndSnapshots.cpp
  src/Library/Snd/SndSnapshots.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Audio/CMakeLists.txt
Labels: 🥺Ready for Review

#1374 enum class MusicId
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/CodeGen/CodeGenOptions.cpp
  src/Bin/CodeGen/CodeGenOptions.h
  src/Engine/MapInfo.cpp
  src/Engine/MapInfo.h
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Audio/SoundEnums.h
Labels: 👍Approved

#1375 Use fmt::join
  src/Engine/Events/EventIR.cpp
Labels: 🥺Ready for Review

#1378 More determinism
  src/Engine/Events/EventMap.cpp
Labels: 🥺Ready for Review

#1381 Win lint issues
  src/Library/Environment/Win/WinEnvironment.cpp
  src/Library/Environment/Win/WinEnvironment.h
Labels: 🥺Ready for Review

#1382 Fix buying price calculation for a character with GM merchant skill.
  src/Engine/PriceCalculator.cpp
  src/Engine/PriceCalculator.h
Labels: 🥺Ready for Review

#1385 Add wand power test
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review

#1346 Better collisions
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Library/Geometry/Vec.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review

#1387 Update test tag
  test/Bin/GameTest/CMakeLists.txt
Labels: 🥺Ready for Review

#1386 remove posting release builds
  .github/workflows/android.yml
Labels: 🥺Ready for Review

#1388 Finishing up enum cleanup
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/MM7.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIDialogues.h
  src/GUI/UI/UIHouses.cpp
  src/Library/Snapshots/CommonSnapshots.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Audio/AudioSamplePool.cpp
  src/Media/Audio/AudioSamplePool.h
  src/Media/Audio/SoundEnums.h
  src/Media/Audio/SoundInfo.h
  src/Media/Audio/SoundList.cpp
  src/Media/Audio/SoundList.h
Labels: 🥺Ready for Review

#1395 Collisions style
  src/Engine/Graphics/Collisions.cpp
Labels: 🥺Ready for Review

#1394 Fix party start position for autosave
  src/Engine/SaveLoad.cpp
Labels: ❓Questions

#1399 Fixing problems with returning a local address
  CMakeLists.txt
  test/Testing/Game/AccessibleVector.h
  thirdparty/CMakeLists.txt
Labels: 🥺Ready for Review

#1401 Don't rely on std::unordered_map working with incomplete types
  src/Library/Snd/SndReader.h
Labels: 🥺Ready for Review

#1393 Fix and test #1368
  src/Engine/Engine.cpp
  src/Engine/Localization.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review

#1402 Fixes
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review

#1406 Checkout game data with LFS
  .github/workflows/build_data_cache.yml
Labels: 🥺Ready for Review

#1407 Allow to manually repopulate the data cache
  .github/workflows/build_data_cache.yml
Labels: 🥺Ready for Review

#1409 LogSink should have a virtual destructor.
  CMakeLists.txt
  src/Library/Logger/LogSink.h
Labels: 🥺Ready for Review

#1405 Added Library/Vid
  src/Library/CMakeLists.txt
  src/Library/Snd/SndReader.cpp
  src/Library/Vid/CMakeLists.txt
  src/Library/Vid/VidReader.cpp
  src/Library/Vid/VidReader.h
  src/Library/Vid/VidSnapshots.cpp
  src/Library/Vid/VidSnapshots.h
  src/Media/CMakeLists.txt
  src/Media/MediaPlayer.cpp
  src/Media/MediaPlayer.h
  src/Utility/Streams/FileInputStream.cpp
  src/Utility/Streams/FileInputStream.h
  src/Utility/Streams/MemoryInputStream.cpp
  src/Utility/Streams/MemoryInputStream.h
Labels: 🥺Ready for Review

#1404 Moving code to GameStarter
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameOver.cpp
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/ClippingFunctions.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/Nuklear.h
  src/Engine/Graphics/Renderer/NullRenderer.cpp
  src/Engine/Graphics/Renderer/RendererFactory.cpp
  src/Engine/Graphics/Renderer/RendererFactory.h
  src/Engine/Graphics/Sprites.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIFont.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UIBranchlessDialogue.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UIStatusBar.cpp
  src/Io/KeyboardActionMapping.cpp
Labels: 🥺Ready for Review

#1412 Better Engine/Random
  src/Application/GameStarter.cpp
  src/Bin/CodeGen/CodeGen.cpp
  src/Engine/Components/CMakeLists.txt
  src/Engine/Components/Control/EngineControlComponent.h
  src/Engine/Components/Deterministic/CMakeLists.txt
  src/Engine/Components/Deterministic/EngineDeterministicComponent.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.h
  src/Engine/Components/Random/CMakeLists.txt
  src/Engine/Components/Random/EngineRandomComponent.cpp
  src/Engine/Components/Random/EngineRandomComponent.h
  src/Engine/Components/Random/TracingRandomEngine.cpp
  src/Engine/Components/Random/TracingRandomEngine.h
  src/Engine/Random/CMakeLists.txt
  src/Engine/Random/Random.cpp
  src/Engine/Random/Random.h
  src/Engine/Random/RandomEngineFactory.cpp
  src/Engine/Random/RandomEngineFactory.h
  src/Engine/Random/RandomEnums.h
  src/Library/Random/MersenneTwisterRandomEngine.h
  src/Library/Random/RandomEngine.h
  test/Bin/GameTest/GameTests.cpp
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
Labels: 🥺Ready for Review

#1414 Check sound needs decompressing
  src/Library/Snd/SndReader.cpp
Labels: 🥺Ready for Review

#1413 Cleanup
  src/Application/Game.cpp
  src/Application/GameStarter.cpp
  src/Application/GameTraceHandler.cpp
  src/Application/GameWindowHandler.cpp
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/LodTool/LodTool.cpp
  src/Bin/LodTool/LodToolOptions.cpp
  src/Bin/LodTool/LodToolOptions.h
  src/Bin/OpenEnroth/OpenEnroth.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.cpp
  src/Engine/Components/Random/EngineRandomComponent.cpp
  src/Engine/Components/Random/EngineRandomComponent.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.h
  src/Engine/Engine.cpp
  src/Engine/LodSpriteCache.cpp
  src/Engine/LodSpriteCache.h
  src/Engine/LodTextureCache.cpp
  src/Engine/LodTextureCache.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/ItemEnumFunctions.h
  src/Engine/Random/Random.h
  src/Engine/Random/RandomEnums.h
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
  src/Library/Cli/CliApp.h
  src/Library/Geometry/BBox.h
  src/Library/LodFormats/CMakeLists.txt
  src/Library/LodFormats/LodFormatEnums.cpp
  src/Library/LodFormats/LodFormats.cpp
  src/Library/Platform/Application/CMakeLists.txt
  src/Library/Platform/Application/PlatformApplication.cpp
  src/Library/Platform/Application/PlatformApplication.h
  src/Library/Platform/Application/PlatformApplicationAware.h
  src/Library/Platform/Application/PlatformComponentStorage.cpp
  src/Library/Platform/Application/PlatformComponentStorage.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/TestController.cpp
Labels: 🥺Ready for Review

#1415 Resolved a TODO involving test retracing
  src/Engine/Objects/Actor.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests.cpp
Labels: 🥺Ready for Review
