Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-05, with the labels that each got.

#752 Refactor character awards displaying
  src/Application/Game.cpp
  src/Engine/Awards.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICharacter.h
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#757 Introduce player skill value class
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Objects/CombinedSkillValue.cpp
  src/Engine/Objects/CombinedSkillValue.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/PlayerEnums.h
Labels: 👍Approved

#759 Some cleanup of mouse right click actions
  src/Application/Game.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Engine.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIPopup.h
  src/Io/Mouse.cpp
Labels: 👍Approved

#761 Use new container for level strings
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Events.cpp
  src/Engine/Events.h
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/EventMap.cpp
  src/Engine/Events/Loader.h
  src/Engine/Events/Processor.cpp
  src/Engine/Events/Processor.h
Labels: ❓Questions

#763 Some changes in save/load UI
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/SaveLoad.h
  src/GUI/UI/UISaveLoad.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#762 Cleanup of item combining function
  src/Engine/Engine.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIPopup.h
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#767 Fix trace recording save loading
  src/Engine/Components/Control/EngineController.cpp
Labels: 👍Approved

#764 Composable binary serialization abstractions
  src/Engine/Graphics/DecorationList.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/ObjectList.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/CMakeLists.txt
  src/Engine/Serialization/CompositeImages.cpp
  src/Engine/Serialization/CompositeImages.h
  src/Engine/Serialization/Deserializer.h
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Serialization/MultiStageSerialization.h
  src/Engine/Serialization/Serializer.h
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/PlayerFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Library/Binary/ArraySerialization.h
  src/Library/Binary/BinaryExceptions.cpp
  src/Library/Binary/BinaryExceptions.h
  src/Library/Binary/BinarySerialization.h
  src/Library/Binary/BlobSerialization.h
  src/Library/Binary/CMakeLists.txt
  src/Library/Binary/MemCopySerialization.h
  src/Library/CMakeLists.txt
  src/Media/Audio/AudioPlayer.cpp
  src/Utility/Streams/OutputStream.h
Labels: 👍Approved

#768 Use std::array for p2DEvents
  src/Engine/Events.cpp
  src/Engine/Events2D.h
Labels: 👍Approved

#766 load game hotfix
  src/GUI/UI/UISaveLoad.cpp
Labels: 🥺Ready for Review

#770 Renamings & docs
  src/Engine/Graphics/DecorationList.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/ObjectList.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/CommonImages.h
  src/Engine/Serialization/CompositeImages.cpp
  src/Engine/Serialization/CompositeImages.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Serialization/MultiStageSerialization.h
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/PlayerFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/GUI/GUIFont.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Library/Binary/ArraySerialization.h
  src/Library/Binary/BinarySerialization.h
  src/Library/Binary/BlobSerialization.h
  src/Library/Binary/MemCopySerialization.h
  src/Library/Serialization/Serialization.h
  src/Media/Audio/AudioPlayer.cpp
Labels: 👍Approved

#771 TODO in GameKeyboardController resolved
  src/Application/Game.cpp
  src/Application/GameKeyboardController.cpp
  src/Application/GameKeyboardController.h
  src/Application/GameWindowHandler.cpp
  src/Application/GameWindowHandler.h
  src/Library/Config/AnyHandler.h
Labels: 👍Approved

#775 Renamings & docs
  src/Application/GameMenu.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/SaveLoad.h
  src/Engine/Serialization/CommonImages.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIShops.cpp
Labels: 👍Approved

#777 Tests for issues
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UISaveLoad.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#778 Enable autorepeat for text input
  src/Application/GameWindowHandler.cpp
Labels: 🥺Ready for Review

#780 Added Blob::subBlob
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
Labels: 👍Approved

#781 Recording starting & ending position in traces now
  src/Application/main.cpp
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Components/Trace/EngineTracePlaybackFlags.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceStateAccessor.cpp
  src/Engine/Components/Trace/EngineTraceStateAccessor.h
  src/Library/Trace/EventTrace.cpp
  src/Library/Trace/EventTrace.h
  test/Bin/GameTest/CMakeLists.txt
Labels: 👍Approved

#787 Sped up odm deserialization
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
Labels: 👍Approved

#793 Check timers only from running game state
  src/Application/Game.cpp
Labels: 👍Approved

#786 Deserialization takes 1ms, no reason to have progress callbacks there
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Serialization/CompositeImages.cpp
  src/Engine/Serialization/CompositeImages.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#785 Fix #783 and #784
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/Items.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/Spells/Spells.cpp
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#789 Rename and move 2devents
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/CMakeLists.txt
  src/Engine/Events.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventMap.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/PriceCalculator.cpp
  src/Engine/PriceCalculator.h
  src/Engine/Tables/BuildingTable.cpp
  src/Engine/Tables/BuildingTable.h
  src/Engine/Tables/CMakeLists.txt
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UIShops.h
  src/GUI/UI/UITransition.cpp
Labels: ❓Questions

#796 Saner implementation of Blob::subBlob
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
Labels: 👍Approved

#795 Record traces at 20fps by default
  src/Application/GameConfig.h
  src/Engine/Components/Trace/EngineTraceStateAccessor.cpp
  test/Bin/GameTest/CMakeLists.txt
Labels: 👍Approved

#788 Cleanup in LegacyImages continued
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/Processor.cpp
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/LocationEnums.h
  src/Engine/Graphics/LocationFunctions.cpp
  src/Engine/Graphics/LocationFunctions.h
  src/Engine/Graphics/LocationInfo.h
  src/Engine/Graphics/LocationTime.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/CompositeImages.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/SpawnPoint.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
Labels: 👍Approved

#800 Do not filter out decorations when holding right click
  src/Engine/Graphics/Vis.cpp
Labels: 👍Approved

#803 Finally get rid of pPlayers array
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIShops.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#806 Dropped some dead code from LOD
  src/Engine/Engine.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
Labels: 👍Approved

#809 Move or remove some more globals
  src/Engine/SaveLoad.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
Labels: 🥺Ready for Review

#810 Move Awards and Autonotes into Tables module
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/CMakeLists.txt
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Tables/AutonoteTable.cpp
  src/Engine/Tables/AutonoteTable.h
  src/Engine/Tables/AwardTable.cpp
  src/Engine/Tables/AwardTable.h
  src/Engine/Tables/CMakeLists.txt
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIBountyHunting.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/AutonotesBook.h
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIShops.cpp
Labels: 🥺Ready for Review

#812 Minor cleanup in asset manager
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameOver.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/TileFrameTable.h
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/Mouse.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#813 Clear empty slot on save
  src/Application/GameMenu.cpp
Labels: 👍Approved

#817 Fix event issues in Bracada Desert
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/Player.cpp
Labels: 🥺Ready for Review

#818 Add a number of new tests
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#827 Resolve more globals from mm7_data
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Level/Decoration.cpp
  src/Engine/Graphics/Level/Decoration.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/MessageScrollTable.cpp
  src/Engine/Tables/MessageScrollTable.h
  src/Engine/Tables/QuestTable.cpp
  src/Engine/Tables/QuestTable.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UITransition.cpp
Labels: 🥺Ready for Review

#829 Add TextureFrameTable to faces
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
Labels: 🥺Ready for Review

#831 Fix camera orientation for positional sound
  src/Media/Audio/OpenALSoundProvider.cpp
Labels: 👍Approved

#834 Make clicking large objects at close distance easier
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Vis.cpp
  src/Engine/Graphics/Vis.h
Labels: 👍Approved

#838 Fix buff popup text color
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#835 Use new skill class almost everywhere
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/PriceCalculator.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  src/Io/KeyboardInputHandler.cpp
Labels: 👍Approved

#839 Move ItemTable to Tables module
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Serialization/CompositeImages.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/FactionTable.cpp
  src/Engine/Tables/FactionTable.h
  src/Engine/Tables/ItemTable.cpp
  src/Engine/Tables/ItemTable.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/Io/Mouse.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#836 Jump spell issues
  .github/workflows/linux.yml
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Party.h
  src/Engine/Spells/CastSpellInfo.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#841 Fix #840 and refactor guild spells generator
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIGuilds.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
Labels: ❓Questions

#847 PaletteManager now stores all palettes
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/PaletteManager.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Objects/Actor.cpp
Labels: 👍Approved

#848 More RAII in PCX code, using size_t here and there
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/PCX.cpp
  src/Engine/Graphics/PCX.h
Labels: 👍Approved

#846 Issue fixes
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
Labels: 👍Approved

#849 Remove stru367.h
  src/Engine/CMakeLists.txt
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/Engine/stru367.h
Labels: 👍Approved

#853 Refactor some globals related to training halls
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Time.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#842 POC of new LOD reader
  src/Engine/CMakeLists.txt
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/GameResourceManager.cpp
  src/Engine/GameResourceManager.h
  src/Engine/Graphics/Image.h
  src/Engine/Tables/BuildingTable.cpp
  src/Library/Lod/CMakeLists.txt
  src/Library/Lod/Internal/LodDirectory.h
  src/Library/Lod/Internal/LodDirectoryHeader.h
  src/Library/Lod/Internal/LodFile.h
  src/Library/Lod/Internal/LodFileHeader.h
  src/Library/Lod/Internal/LodHeader.h
  src/Library/Lod/LodDefinitions.h
  src/Library/Lod/LodReader.cpp
  src/Library/Lod/LodReader.h
Labels: 👍Approved

#854 Add some cmakefiles
  src/Application/Game.cpp
  src/GUI/CMakeLists.txt
  src/GUI/UI/Books/CMakeLists.txt
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/UISpellbook.cpp
  src/GUI/UI/UISpellbook.h
  src/Media/Audio/CMakeLists.txt
  src/Media/CMakeLists.txt
Labels: 👍Approved

#852 Dropped IndexedArray overloading
  src/Application/GameKeyboardController.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/NPCEnums.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIPopup.cpp
  src/Platform/PlatformEnums.h
  src/Utility/IndexedArray.h
  src/Utility/Tests/IndexedArray_ut.cpp
Labels: 👍Approved

#851 Codestyle in Utility/Streams
  src/Utility/Streams/MemoryInputStream.cpp
  src/Utility/Streams/MemoryInputStream.h
  src/Utility/Streams/StringOutputStream.cpp
  src/Utility/Streams/StringOutputStream.h
Labels: 👍Approved

#850 More cleanup in PCX code
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/PCX.cpp
  src/Engine/Graphics/PCX.h
Labels: 👍Approved

#857 First test for #735
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#858 Renamings & docs in Timer
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Time.cpp
  src/Engine/Time.h
Labels: 👍Approved

#856 Some cleanup in IndexedArray & IndexedBitset
  src/Utility/CMakeLists.txt
  src/Utility/IndexedArray.h
  src/Utility/IndexedBitset.h
  src/Utility/Tests/IndexedArray_ut.cpp
  src/Utility/Tests/IndexedBitset_ut.cpp
Labels: 👍Approved

#860 Added 2nd test for #735
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#845 Refactor actor AI update functions and remove some global arrays
  src/Engine/Objects/Actor.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
Labels: 👍Approved

#861 Added BlobInputStream, using it in LodReader
  src/Engine/GameResourceManager.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Library/Lod/LodReader.cpp
  src/Library/Lod/LodReader.h
  src/Utility/CMakeLists.txt
  src/Utility/Streams/BlobInputStream.cpp
  src/Utility/Streams/BlobInputStream.h
Labels: 👍Approved

#859 Beginning of houses UI refactoring, magic guild refactor
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIBountyHunting.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/Houses/CMakeLists.txt
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MagicGuild.h
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIGuilds.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIShops.cpp
Labels: ❓Questions

#863 Use new lod code for whole events.lod
  src/Engine/Engine.cpp
  src/Engine/Events/Loader.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/Localization.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Tables/AutonoteTable.cpp
  src/Engine/Tables/AwardTable.cpp
  src/Engine/Tables/FactionTable.cpp
  src/Engine/Tables/ItemTable.cpp
  src/Engine/Tables/MessageScrollTable.cpp
  src/Engine/Tables/QuestTable.cpp
  src/Engine/Tables/StorylineTextTable.cpp
  src/GUI/UI/UICredits.cpp
Labels: 👍Approved

#864 BlobInputStream can now be used to cut up a Blob into more Blobs
  src/Engine/GameResourceManager.cpp
  src/Library/Lod/LodReader.cpp
  src/Utility/Streams/BlobInputStream.cpp
  src/Utility/Streams/BlobInputStream.h
Labels: 🥺Ready for Review

#870 snake case enum
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/LocationEnums.h
  src/Engine/Graphics/LocationFunctions.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Media/Audio/AudioPlayer.cpp
Labels: 👍Approved

#874 Added struct Color & using it everywhere
  src/Application/GameOver.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Viewport.h
  src/Engine/Graphics/Weather.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIButton.cpp
  src/GUI/GUIButton.h
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/Houses/Jail.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIPopup.h
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UIStatusBar.cpp
  src/GUI/UI/UIStatusBar.h
  src/GUI/UI/UITransition.cpp
  src/Io/Mouse.cpp
  src/Library/Color/Color.h
Labels: 👍Approved

#875 Refactor houses UI: Bank and Temple
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/Houses/Bank.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Temple.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#879 Moved ColorTable into separate h/cpp files
  src/Engine/AssetsManager.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/SpellFxRenderer.h
  src/Library/Color/CMakeLists.txt
  src/Library/Color/Color.cpp
  src/Library/Color/Color.h
  src/Library/Color/ColorTable.cpp
  src/Library/Color/ColorTable.h
Labels: 👍Approved

#869 Minor cleanup
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Spells/CastSpellInfo.cpp
Labels: 👍Approved

#882 Dropped HWL support.
  resources/shaders/glbillbshader.frag
  resources/shaders/gltwodshader.frag
  src/Application/GameConfig.h
  src/Engine/Graphics/HWLContainer.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Graphics/Sprites.cpp
  src/Engine/LOD.cpp
  src/Utility/DataPath.cpp
Labels: 👍Approved

#883 snake case player conditions
  src/Application/Game.cpp
  src/Engine/Conditions.cpp
  src/Engine/Conditions.h
  src/Engine/Engine.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/PriceCalculator.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#884 reduce logger output
  src/Application/GameConfig.cpp
  src/Application/GameStarter.cpp
  test/Bin/GameTest/GameTestOptions.cpp
Labels: 👍Approved

#885 retrace and combine tests
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#886 Cleanup
  resources/shaders/glbillbshader.frag
  resources/shaders/gltwodshader.frag
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestOptions.cpp
Labels: 👍Approved

#889 Renamed ArraySerialization -> ContainerSerialization
  src/Library/Binary/BinarySerialization.h
  src/Library/Binary/CMakeLists.txt
  src/Library/Binary/ContainerSerialization.h
Labels: 👍Approved

#888 More fmt & more std::string everywhere
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/Sprites.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/NPC.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/IconFrameTable.h
  src/Engine/Tables/ItemTable.cpp
  src/GUI/GUIBountyHunting.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UISpellbook.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardActionMapping.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/KeyboardInputHandler.h
  src/Media/MediaLogger.cpp
Labels: 👍Approved

#890 Preparing to drop different image formats
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Objects/Chest.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#893 Remove global award and autonote string buffer
  src/Engine/Objects/Player.cpp
  src/Engine/Tables/AutonoteTable.cpp
  src/Engine/Tables/AutonoteTable.h
  src/Engine/Tables/AwardTable.cpp
  src/Engine/Tables/AwardTable.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
Labels: 👍Approved

#892 Fix playing time shift in magic guild
  src/GUI/UI/Houses/MagicGuild.cpp
Labels: 👍Approved

#898 More sprintf calls replaced with fmt calls
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#896 Dropped IMAGE_FORMAT, using Color where appropriate
  src/Arcomage/Arcomage.cpp
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/ImageFormatConverter.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/OpenGL/TextureOpenGL.cpp
  src/Engine/Graphics/OpenGL/TextureOpenGL.h
  src/Engine/Graphics/PCX.cpp
  src/Engine/Graphics/PCX.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Objects/Player.cpp
  src/Engine/SaveLoad.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIGame.cpp
  src/Library/Color/Color.h
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#891 Refactor houses UI: Training
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/mm7_data.h
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Training.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#900 Refactor houses UI: Tavern
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Tavern.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍👍Very Approved, ❓Questions

#901 Remove even more raw strings from tables
  src/Engine/Events/EventIR.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemEnchantment.h
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Tables/BuildingTable.cpp
  src/Engine/Tables/BuildingTable.h
  src/Engine/Tables/ItemTable.cpp
  src/Engine/Tables/ItemTable.h
  src/Engine/Tables/MessageScrollTable.cpp
  src/Engine/Tables/MessageScrollTable.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved
