Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-07, with the labels that each got.

#1030 Partial cleanup of house NPC dialogue
  src/Application/Game.cpp
  src/GUI/GUIEnums.h
  src/GUI/UI/NPCTopics.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 🥺Ready for Review

#1031 Use enum for NPC greet type
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/GUI/UI/UIDialogue.cpp
Labels: 🥺Ready for Review

#1032 fix #742
  src/Engine/Party.cpp
  src/GUI/UI/UIPartyCreation.cpp
Labels: 🥺Ready for Review

#1043 issue fixes
  README.md
  src/Application/Game.cpp
  src/Engine/Objects/Character.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1046 Tracing improvements
  src/Application/Game.cpp
  src/Application/main.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.h
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Components/Trace/EngineTraceComponent.cpp
  src/Engine/Components/Trace/EngineTraceEnums.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.h
  src/Engine/Components/Trace/EngineTraceSimplePlayer.cpp
  src/Engine/Components/Trace/EngineTraceSimplePlayer.h
  src/Engine/Components/Trace/EngineTraceSimpleRecorder.cpp
  src/Engine/Components/Trace/EngineTraceSimpleRecorder.h
  src/Library/Trace/EventTrace.cpp
  src/Library/Trace/EventTrace.h
  src/Library/Trace/PaintEvent.h
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1048 Update game tests to check afterLoadRandomState
  test/Bin/GameTest/CMakeLists.txt
Labels: 🥺Ready for Review

#1005 Collision fixes, jumps now work reliably outdoors
  src/Application/main.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Utility/Geometry/Plane.h
  src/Utility/Geometry/Vec.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestMain.cpp
  test/Bin/GameTest/GameTestOptions.cpp
  test/Bin/GameTest/GameTestOptions.h
  test/Testing/Game/TestController.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1047 Fixing warnings
  src/Arcomage/Arcomage.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.h
  src/Engine/Spells/Spells.cpp
  src/Engine/mm7text_ru.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIStatusBar.cpp
  src/GUI/UI/UIStatusBar.h
Labels: 🥺Ready for Review

#1052 Fix #1051 and add a test
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1055 Don't access sprite LOD private fields from Vis code
  src/Engine/Engine.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/Vis.cpp
Labels: 👍Approved

#1054 Propagate CombinedSkillValue & fix #1045
  src/Application/Game.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/CharacterEnums.h
  src/Engine/Objects/CombinedSkillValue.cpp
  src/Engine/Objects/CombinedSkillValue.h
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/Engine/Spells/SpellBuff.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#1056 Use ints for face/sector/node ids
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/BspRenderer.h
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/LightsStack.cpp
  src/Engine/Graphics/LightsStack.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/RenderEntities.h
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#1053 Can set log level from command line
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GameConfig.h
  src/Application/GameOptions.cpp
  src/Application/GameStarter.cpp
  src/Application/GameStarterOptions.h
  src/Engine/AssetsManager.cpp
  src/Engine/Components/Trace/EngineTraceStateAccessor.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/GLShaderLoader.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Tables/ItemTable.cpp
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIGame.cpp
  src/Library/Serialization/SerializationFwd.h
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#1057 Some additional checks in tests
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1058 Fix test 293a
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1059 Dropped intercept displacements
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
Labels: 🥺Ready for Review

#1060 Sane interface for Vec3::rotate
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/GUI/UI/UIPopup.cpp
  src/Utility/Geometry/BBox.h
  src/Utility/Geometry/Vec.h
Labels: 🥺Ready for Review

#1061 Cleanup around BBox, all BBox manipulations are now inside BBox class
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Utility/Geometry/BBox.h
Labels: 🥺Ready for Review

#1063 using enum CURRENT_SCREEN
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/SaveLoad.cpp
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UISpellbook.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/MediaPlayer.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1062 More test cleanup & taping for tests
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceSimplePlayer.cpp
  src/Engine/Components/Trace/EngineTraceSimplePlayer.h
  test/Testing/Game/CMakeLists.txt
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
  test/Testing/Game/TestTape.h
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#1065 Better BlobInputStream
  src/Utility/Streams/BlobInputStream.cpp
  src/Utility/Streams/BlobInputStream.h
Labels: 🥺Ready for Review

#1066 Test for Blob::fromFile
  src/Utility/CMakeLists.txt
  src/Utility/Memory/Blob.h
  src/Utility/Memory/Tests/Blob_ut.cpp
Labels: 👍Approved

#1067 More tape usage in tests
  test/Testing/Game/TestTape.h
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1073 Dropped Planei
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UIGame.cpp
  src/Utility/Geometry/Plane.h
Labels: 👍Approved

#1072 Dropped IndoorCameraD3D_Vec4
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/BspRenderer.h
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Camera.h
  src/Engine/Graphics/ClippingFunctions.cpp
  src/Engine/Graphics/ClippingFunctions.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/PortalFunctions.h
  src/Engine/Graphics/Vis.cpp
  src/Engine/Graphics/Vis.h
Labels: 👍Approved

#1071 Cleanup & TODOs in SpriteFrameTable
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/Sprites.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
Labels: 👍Approved

#1070 Minor cleanup in ProcessPartyActions functions
  src/Engine/Engine.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
Labels: 👍Approved

#1074 Resolved a couple TODOs
  src/Engine/Conditions.cpp
  src/Engine/Conditions.h
  src/Engine/Graphics/ClippingFunctions.cpp
  src/Engine/Graphics/ClippingFunctions.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Snapshots/EntitySnapshots.h
  src/Utility/Geometry/Vec.h
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#1064 LodFile* classes work on top of LodReader
  CMakeLists.txt
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/IRender.cpp
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Library/Lod/LodReader.cpp
Labels: 🥺Ready for Review

#1076 Fix #1068 & more powerful taping for tests
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/CharacterEnums.h
  test/Bin/GameTest/CMakeLists.txt
  test/Testing/Game/CMakeLists.txt
  test/Testing/Game/TestController.h
  test/Testing/Game/TestTape.h
  test/Testing/Game/TestVector.h
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#1078 Fixes #1040
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1079 Docs & minor changes in test code
  test/Testing/Game/TestController.h
  test/Testing/Game/TestTape.h
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1080 Working on class Pid, adding type safety as I go
  src/Engine/Objects/Actor.cpp
Labels: 🥺Ready for Review

#1081 Moved out texture/sprite caches from LOD.h/cpp
  src/Application/Game.cpp
  src/Engine/CMakeLists.txt
  src/Engine/Engine.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/PaletteManager.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/LodSpriteCache.cpp
  src/Engine/LodSpriteCache.h
  src/Engine/LodTextureCache.cpp
  src/Engine/LodTextureCache.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/GUI/GUIFont.cpp
Labels: 🥺Ready for Review

#1084 Moved OpenEnroth binary to src/Bin
  CMakeLists.txt
  src/Bin/CMakeLists.txt
  src/Bin/OpenEnroth/CMakeLists.txt
  src/Bin/OpenEnroth/main.cpp
  src/CMakeLists.txt
Labels: 👍Approved

#1083 Mostly enum codestyle
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/Nuklear.cpp
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICharacter.h
  src/GUI/UI/UIGameOver.h
  src/GUI/UI/UIPopup.cpp
  src/Io/Mouse.cpp
Labels: 👍Approved

#1082 Class Pid & trace-only turn-based tests
  src/Application/Game.cpp
  src/Engine/AttackList.cpp
  src/Engine/AttackList.h
  src/Engine/CMakeLists.txt
  src/Engine/Events/EventInterpreter.h
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/RenderEntities.h
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Graphics/Vis.h
  src/Engine/MM7.h
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/Pid.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/SpawnPoint.h
  src/Engine/Spells/Spells.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/Engine/TurnEngine/TurnEngine.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/Media/Audio/AudioPlayer.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#1085 Renamings in Bin/OpenEnroth
  src/Application/CMakeLists.txt
  src/Bin/OpenEnroth/CMakeLists.txt
  src/Bin/OpenEnroth/OpenEnroth.cpp
  src/Bin/OpenEnroth/OpenEnrothOptions.cpp
  src/Bin/OpenEnroth/OpenEnrothOptions.h
Labels: 🥺Ready for Review

#1087 Dropped Engine_DeinitializeAndTerminate, always exiting from main
  src/Application/GameWindowHandler.cpp
  src/Application/GameWindowHandler.h
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Objects/Actor.cpp
Labels: 🥺Ready for Review

#1088 Pid work continued
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/Processor.cpp
  src/Engine/Events/Processor.h
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
Labels: 🥺Ready for Review

#1090 More Pid
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/EventInterpreter.h
  src/Engine/Events/Processor.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Chest.h
  src/GUI/UI/UIPopup.cpp
Labels: 🥺Ready for Review

#1089 Codegen & more
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GameConfig.h
  src/Application/GameStarter.cpp
  src/Application/GameStarterOptions.h
  src/Bin/CMakeLists.txt
  src/Bin/CodeGen/CMakeLists.txt
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/CodeGen/CodeGenOptions.cpp
  src/Bin/CodeGen/CodeGenOptions.h
  src/Bin/OpenEnroth/OpenEnrothOptions.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/MapEnums.h
  src/Engine/MapInfo.cpp
  src/Engine/MapInfo.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Tables/BuildingTable.cpp
  src/Engine/Tables/BuildingTable.h
  src/Engine/Tables/ItemTable.cpp
  src/Engine/Tables/ItemTable.h
  src/Engine/Tables/NPCTable.cpp
  src/Engine/Tables/NPCTable.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UITransition.cpp
  src/GUI/UI/UITransition.h
  src/Library/Lod/LodReader.cpp
  src/Library/Lod/LodReader.h
  src/Media/Audio/AudioPlayer.cpp
  test/Bin/GameTest/GameTestOptions.cpp
  test/Bin/GameTest/GameTestOptions.h
Labels: 🥺Ready for Review

#1091 Style & TODOs
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/CodeGen/CodeGenOptions.cpp
  src/Bin/CodeGen/CodeGenOptions.h
  src/Bin/OpenEnroth/OpenEnroth.cpp
  src/Bin/OpenEnroth/OpenEnrothOptions.cpp
  src/Bin/OpenEnroth/OpenEnrothOptions.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Graphics/ClippingFunctions.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Localization.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/GUI/GUIProgressBar.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MagicGuild.h
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/NPCTopics.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/Library/Compression/Compression.cpp
  src/Library/Compression/Compression.h
  src/Library/Trace/EventTrace.cpp
  src/Platform/PlatformEvents.h
  src/Platform/Sdl/SdlEventLoop.cpp
  src/Utility/Geometry/Vec.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Bin/GameTest/GameTestOptions.cpp
  test/Bin/GameTest/GameTestOptions.h
Labels: 🥺Ready for Review

#1092 Cleaned up how thirdparty includes are handled
  .github/workflows/linux-release.yml
  .github/workflows/linux.yml
  .github/workflows/style.yml
  CMakeLists.txt
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/Camera.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/Nuklear.h
  src/Engine/Graphics/NuklearEventHandler.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/Vis.h
  src/GUI/UI/Houses/CMakeLists.txt
  src/GUI/UI/UIHouses.cpp
  src/Library/Config/CMakeLists.txt
  src/Library/Json/CMakeLists.txt
  src/Library/Serialization/CMakeLists.txt
  src/Utility/CMakeLists.txt
  test/Tests/CMakeLists.txt
  thirdparty/CMakeLists.txt
  thirdparty/nuklear/CMakeLists.txt
Labels: 🥺Ready for Review

#1096 fix #1094
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#1099 Cleaned up cmake files
  .github/workflows/macos-release.yml
  .github/workflows/macos.yml
  CMakeLists.txt
  CMakeModules/Dependencies.cmake
  android/openenroth/jni/CMakeLists.txt
  src/Application/CMakeLists.txt
  src/Arcomage/CMakeLists.txt
  src/Bin/CodeGen/CMakeLists.txt
  src/Bin/OpenEnroth/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/Engine/Components/Control/CMakeLists.txt
  src/Engine/Components/Deterministic/CMakeLists.txt
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Events/CMakeLists.txt
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Snapshots/CMakeLists.txt
  src/Engine/Spells/CMakeLists.txt
  src/Engine/Tables/CMakeLists.txt
  src/Engine/TurnEngine/CMakeLists.txt
  src/GUI/CMakeLists.txt
  src/GUI/UI/Books/CMakeLists.txt
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/Houses/CMakeLists.txt
  src/Io/CMakeLists.txt
  src/Library/Application/CMakeLists.txt
  src/Library/Binary/CMakeLists.txt
  src/Library/Color/CMakeLists.txt
  src/Library/Compression/CMakeLists.txt
  src/Library/Config/CMakeLists.txt
  src/Library/Image/CMakeLists.txt
  src/Library/Json/CMakeLists.txt
  src/Library/Lod/CMakeLists.txt
  src/Library/Logger/CMakeLists.txt
  src/Library/Serialization/CMakeLists.txt
  src/Library/Trace/CMakeLists.txt
  src/Media/Audio/CMakeLists.txt
  src/Media/CMakeLists.txt
  src/Platform/CMakeLists.txt
  src/Utility/CMakeLists.txt
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/UnitTest/CMakeLists.txt
  test/Testing/Extensions/CMakeLists.txt
  test/Testing/Game/CMakeLists.txt
  test/Testing/Unit/CMakeLists.txt
  test/Tests/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: 🥺Ready for Review

#1100 Fix and test #1093
  src/Engine/Spells/CastSpellInfo.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1101 Minor cleanup in status bar, added status bar checks to #1093 test
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/GUI/UI/UIStatusBar.cpp
  src/GUI/UI/UIStatusBar.h
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1102 Dropping #ifdefs for older SDL versions
  src/Platform/Sdl/SdlGamepad.cpp
  src/Platform/Sdl/SdlPlatform.cpp
Labels: 👍Approved

#1103 Better handling of binary serialization overloads
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Snapshots/CommonSnapshots.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
  src/Engine/Snapshots/SnapshotSerialization.h
  src/Library/Binary/BinaryConcepts.h
  src/Library/Binary/BinarySerialization.h
  src/Library/Binary/BinaryTags.h
  src/Library/Binary/BlobSerialization.h
  src/Library/Binary/CMakeLists.txt
  src/Library/Binary/ContainerSerialization.h
  src/Library/Binary/MemCopySerialization.h
Labels: 🥺Ready for Review

#1104 Got rid of c_str calls that are not needed anymore
  src/Application/Game.cpp
  src/Application/GameOver.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UITransition.cpp
Labels: 👍Approved

#1105 Breaking up Engine/Snapshots
  src/Engine/Graphics/DecorationList.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/ObjectList.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/CMakeLists.txt
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/TableSerialization.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Library/CMakeLists.txt
  src/Library/Snapshots/CMakeLists.txt
  src/Library/Snapshots/CommonSnapshots.h
  src/Library/Snapshots/SnapshotSerialization.h
  src/Media/Audio/AudioPlayer.cpp
Labels: 👍Approved

#1111 require cmake 3.24 on linux
  CMakeLists.txt
  android/openenroth/build.gradle
  src/Application/CMakeLists.txt
  src/Arcomage/CMakeLists.txt
  src/Bin/CMakeLists.txt
  src/Bin/CodeGen/CMakeLists.txt
  src/Bin/OpenEnroth/CMakeLists.txt
  src/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/Engine/Components/CMakeLists.txt
  src/Engine/Components/Control/CMakeLists.txt
  src/Engine/Components/Deterministic/CMakeLists.txt
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Events/CMakeLists.txt
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Snapshots/CMakeLists.txt
  src/Engine/Spells/CMakeLists.txt
  src/Engine/Tables/CMakeLists.txt
  src/Engine/TurnEngine/CMakeLists.txt
  src/GUI/CMakeLists.txt
  src/GUI/UI/Books/CMakeLists.txt
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/Houses/CMakeLists.txt
  src/Io/CMakeLists.txt
  src/Library/Application/CMakeLists.txt
  src/Library/Binary/CMakeLists.txt
  src/Library/CMakeLists.txt
  src/Library/Color/CMakeLists.txt
  src/Library/Compression/CMakeLists.txt
  src/Library/Config/CMakeLists.txt
  src/Library/Image/CMakeLists.txt
  src/Library/Json/CMakeLists.txt
  src/Library/Lod/CMakeLists.txt
  src/Library/Logger/CMakeLists.txt
  src/Library/Random/CMakeLists.txt
  src/Library/Serialization/CMakeLists.txt
  src/Library/Snapshots/CMakeLists.txt
  src/Library/Trace/CMakeLists.txt
  src/Media/Audio/CMakeLists.txt
  src/Media/CMakeLists.txt
  src/Platform/CMakeLists.txt
  src/Utility/CMakeLists.txt
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/UnitTest/CMakeLists.txt
  test/CMakeLists.txt
  test/Testing/CMakeLists.txt
  test/Testing/Extensions/CMakeLists.txt
  test/Testing/Game/CMakeLists.txt
  test/Testing/Unit/CMakeLists.txt
  test/Tests/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: 👍Approved

#1116 Fix stack corruption in ArenaFight. Issue 1115.
  src/GUI/UI/NPCTopics.cpp
Labels: 👍Approved

#1107 SDL finger events fix by @yarolig
  src/Platform/Sdl/SdlEventLoop.cpp
  src/Platform/Sdl/SdlEventLoop.h
Labels: 🥺Ready for Review

#1109 Link with SDL dynamically on Android
  thirdparty/CMakeLists.txt
Labels: 🥺Ready for Review

#1123 Added InputStream::skipOrFail
  src/Utility/Streams/InputStream.cpp
  src/Utility/Streams/InputStream.h
Labels: 👍Approved

#1118 Move scripted NPC topic selection processing into NPCTopics
  src/Application/Game.cpp
  src/GUI/UI/NPCTopics.cpp
  src/GUI/UI/NPCTopics.h
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#1121 resolve amd shader compile error
  resources/shaders/glbillbshader.frag
  resources/shaders/glbspshader.frag
  resources/shaders/gldecalshader.frag
  resources/shaders/glforcepershader.frag
  resources/shaders/gllinesshader.frag
  resources/shaders/glnuklear.frag
  resources/shaders/gloutbuild.frag
  resources/shaders/glterrain.frag
  resources/shaders/gltextshader.frag
  resources/shaders/gltwodshader.frag
Labels: 👍Approved

#1127 Updated LodReader
  CMakeLists.txt
  src/Bin/CodeGen/CodeGen.cpp
  src/Engine/GameResourceManager.cpp
  src/Engine/GameResourceManager.h
  src/Engine/LOD.cpp
  src/Engine/LodSpriteCache.cpp
  src/Engine/LodSpriteCache.h
  src/Engine/LodTextureCache.cpp
  src/Engine/LodTextureCache.h
  src/Library/Lod/CMakeLists.txt
  src/Library/Lod/LodDefinitions.h
  src/Library/Lod/LodEnums.cpp
  src/Library/Lod/LodEnums.h
  src/Library/Lod/LodReader.cpp
  src/Library/Lod/LodReader.h
  src/Library/Lod/LodSnapshots.cpp
  src/Library/Lod/LodSnapshots.h
  src/Library/Trace/EventTrace.h
  src/Utility/Streams/FileInputStream.h
  src/Utility/String.cpp
  src/Utility/String.h
Labels: 👍Approved

#1128 Don't route GraphicsImage creation through IRender
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/SaveLoad.cpp
  src/GUI/GUIFont.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#1131 Dropped TEST_GROUP
  src/Library/Json/CMakeLists.txt
  src/Library/Serialization/CMakeLists.txt
  src/Library/Snapshots/CMakeLists.txt
  src/Utility/CMakeLists.txt
  test/Bin/GameTest/CMakeLists.txt
  test/Testing/Game/CMakeLists.txt
  test/Testing/Game/GameTest.h
  test/Testing/Unit/CMakeLists.txt
  test/Testing/Unit/UnitTest.h
  test/Tests/CMakeLists.txt
Labels: 🥺Ready for Review

#1137 add data cache workflow
  .github/workflows/android.yml
  .github/workflows/build_data_cache
  .github/workflows/build_release.yml
  .github/workflows/doxygen.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/shaders.yml
  .github/workflows/style.yml
  .github/workflows/windows.yml
Labels: 👍Approved

#1132 Better arcomage fix
  src/Arcomage/Arcomage.cpp
  src/Arcomage/Arcomage.h
  src/Arcomage/ArcomageCards.cpp
Labels: ❓Questions

#1142 Fixed Windows game tests
  src/Engine/Graphics/RenderNull.cpp
Labels: 👍Approved

#1136 Don't cancel workflow runs on new commits
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: 👍Approved

#1141 Tests don't crash if we have an exception in main thread
  src/Engine/Components/Control/EngineControlComponent.cpp
  src/Engine/Components/Control/EngineControlComponent.h
  src/Engine/Components/Control/EngineControlState.h
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Library/Application/PlatformApplication.cpp
  src/Library/Application/PlatformApplication.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/GameTest.cpp
  test/Testing/Game/GameTest.h
  test/Testing/Unit/UnitTest.h
Labels: 🥺Ready for Review

#1143 Lod-specific file formats code is now in Library/LodFormats
  src/Engine/CMakeLists.txt
  src/Engine/GameResourceManager.cpp
  src/Engine/GameResourceManager.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/PaletteManager.h
  src/Engine/Graphics/Texture_MM7.cpp
  src/Engine/Graphics/Texture_MM7.h
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/LodSpriteCache.cpp
  src/Engine/LodSpriteCache.h
  src/Engine/LodTextureCache.cpp
  src/Engine/SaveLoad.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/Library/CMakeLists.txt
  src/Library/Lod/CMakeLists.txt
  src/Library/Lod/LodReader.cpp
  src/Library/Lod/LodSnapshots.h
  src/Library/LodFormats/CMakeLists.txt
  src/Library/LodFormats/LodFormatEnums.h
  src/Library/LodFormats/LodFormatSnapshots.h
  src/Library/LodFormats/LodFormats.cpp
  src/Library/LodFormats/LodFormats.h
Labels: 🥺Ready for Review

#1146 use released ndk
  .github/workflows/android.yml
  .github/workflows/build_all.yml
  .github/workflows/build_release.yml
  android/openenroth/build.gradle
Labels: 👍Approved

#1149 Fix x86 linux game tests
  .github/workflows/linux.yml
  CMakeLists.txt
Labels: 🥺Ready for Review

#1147 Call all of cmath with std prefix
  src/Application/Game.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/OurMath.cpp
  src/Engine/OurMath.h
  src/Engine/Party.cpp
  src/Engine/PriceCalculator.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/mm7text_ru.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UIGame.cpp
  src/Io/Mouse.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
Labels: 🥺Ready for Review

#1150 Add -Werror=suggest-override
  CMakeLists.txt
  src/Engine/Graphics/RenderNull.cpp
  src/Engine/LOD.h
  src/GUI/UI/Books/AutonotesBook.h
  src/GUI/UI/Books/CalendarBook.h
  src/GUI/UI/Books/JournalBook.h
  src/GUI/UI/Books/LloydsBook.h
  src/GUI/UI/Books/MapBook.h
  src/GUI/UI/Books/QuestBook.h
  src/GUI/UI/Books/TownPortalBook.h
  src/GUI/UI/UIBooks.h
  src/GUI/UI/UICharacter.h
  src/GUI/UI/UIChest.h
  src/GUI/UI/UICredits.h
  src/GUI/UI/UIDialogue.h
  src/GUI/UI/UIGame.h
  src/GUI/UI/UIGameOver.h
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIInventory.h
  src/GUI/UI/UIMainMenu.h
  src/GUI/UI/UIPartyCreation.h
  src/GUI/UI/UIQuickReference.h
  src/GUI/UI/UIRest.h
  src/GUI/UI/UISaveLoad.h
  src/GUI/UI/UISpellbook.h
  src/GUI/UI/UITransition.h
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#1154 Preparations for LodWriter
  src/Engine/Engine.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/Engine/SaveLoad.cpp
  src/Engine/SaveLoad.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
  src/GUI/UI/UISaveLoad.cpp
  src/Library/Lod/LodEnums.h
  src/Library/Lod/LodReader.cpp
  src/Library/Lod/LodReader.h
Labels: 🥺Ready for Review

#1159 cache fixes
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: 👍Approved

#1156 Don't show message boxes in game tests & some cmake fixes
  CMakeLists.txt
  CMakeModules/Dependencies.cmake
  src/Bin/OpenEnroth/OpenEnroth.cpp
  src/Engine/ErrorHandling.cpp
  src/Engine/ErrorHandling.h
Labels: 🥺Ready for Review

#1158 Reopen std streams on Windows only when there's none
  src/Application/GameStarter.cpp
  src/Platform/PlatformEnums.h
  src/Platform/Win/WinPlatform.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/UnitTest/CMakeLists.txt
Labels: 🥺Ready for Review

#1153 Null platform & running game tests windowless
  .github/workflows/build_all.yml
  .github/workflows/build_release.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Application/GameStarterOptions.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/RenderNull.cpp
  src/Library/Application/PlatformApplication.cpp
  src/Library/Application/PlatformApplication.h
  src/Platform/CMakeLists.txt
  src/Platform/Null/NullEventLoop.cpp
  src/Platform/Null/NullEventLoop.h
  src/Platform/Null/NullOpenGLContext.cpp
  src/Platform/Null/NullOpenGLContext.h
  src/Platform/Null/NullPlatform.cpp
  src/Platform/Null/NullPlatform.h
  src/Platform/Null/NullPlatformOptions.h
  src/Platform/Null/NullPlatformSharedState.h
  src/Platform/Null/NullWindow.cpp
  src/Platform/Null/NullWindow.h
  test/Bin/GameTest/GameTestOptions.h
Labels: 🥺Ready for Review

#1165 Fix the timing of "no" character expression
  src/Engine/Objects/Character.cpp
  src/Engine/Party.cpp
  src/Engine/Tables/CharacterFrameTable.cpp
  src/Engine/Tables/CharacterFrameTable.h
Labels: 🥺Ready for Review

#1166 Make OE a console app on Windows
  src/Application/GameStarter.cpp
  src/Bin/OpenEnroth/CMakeLists.txt
  src/Platform/PlatformEnums.h
  src/Platform/PlatformLogger.h
  src/Platform/Posix/PosixPlatform.cpp
  src/Platform/Win/WinPlatform.cpp
Labels: 🥺Ready for Review

#1168 Fix regression with config not being loaded
  .github/workflows/build_all.yml
  .github/workflows/build_release.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GameStarter.cpp
  src/Application/GameStarterOptions.h
  src/Library/Config/AnyConfigEntry.cpp
  src/Library/Config/AnyConfigEntry.h
  src/Library/Config/ConfigEntry.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestMain.cpp
  test/Bin/GameTest/GameTestOptions.cpp
Labels: 🥺Ready for Review

#1170 error on Mingw
  CMakeModules/Detection.cmake
Labels: ❓Questions

#1172 Fix and test #1155
  src/GUI/UI/UIDialogue.cpp
  src/Io/Mouse.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1171 Propagating Pid usage
  CMakeModules/Detection.cmake
  src/Application/GameMenu.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/UIPopup.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Audio/SoundEnums.h
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1169 use recommended optimizations in debug builds
  .github/workflows/android.yml
  .github/workflows/build_all.yml
  .github/workflows/build_release.yml
  .github/workflows/doxygen.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/shaders.yml
  .github/workflows/style.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  thirdparty/luajit/CMakeLists.txt
  thirdparty/luajit/cmake/src/CMakeLists.txt
  thirdparty/luajit/cmake/src/host/cmake/buildvm/CMakeLists.txt
  thirdparty/luajit/cmake/src/host/cmake/minilua/CMakeLists.txt
Labels: 👍Approved

#1176 More Pid work
  src/Application/Game.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.h
  src/Engine/Pid.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/Io/Mouse.h
Labels: 👍Approved
