Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-02, with the labels that each got.

#396 Hotfixes for tracing & test for issue 294 (currently fails)
  src/Engine/Plugins/EngineController.cpp
  src/Engine/Plugins/EngineController.h
  src/Engine/Plugins/EngineTracer.cpp
  src/Platform/Sdl/SdlEventLoop.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestMain.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#398 Mostly cleaning up enums
  src/Application/Game.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/Level/Decoration.h
  src/Engine/Graphics/ParticleEngine.h
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Graphics/Vis.h
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Objects/NPCEnums.h
  src/Engine/Party.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Spells/CMakeLists.txt
  src/Engine/TurnEngine/TurnEngine.cpp
  src/Engine/TurnEngine/TurnEngine.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIGame.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  src/Library/Serialization/Tests/Serialization_ut.cpp
Labels: 🥺Ready for Review

#399 Moved compression to Library
  src/Engine/CMakeLists.txt
  src/Engine/Graphics/HWLContainer.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/LOD.cpp
  src/Engine/SaveLoad.cpp
  src/Library/CMakeLists.txt
  src/Library/Compression/CMakeLists.txt
  src/Library/Compression/Compression.cpp
  src/Library/Compression/Compression.h
  src/Library/Lod/CMakeLists.txt
  src/Library/Lod/LodReader.cpp
  src/Library/Random/Random.h
  src/Media/Audio/AudioPlayer.cpp
Labels: 🥺Ready for Review

#397 Tracing hotfixes++
  src/Arcomage/Arcomage.cpp
  src/Arcomage/Arcomage.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/FrameLimiter.cpp
  src/Engine/Graphics/FrameLimiter.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.h
  src/Engine/Plugins/EngineController.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
Labels: 🥺Ready for Review

#401 Codestyle & TODOs in Platform code
  src/Application/Game.cpp
  src/Application/GameTraceHandler.cpp
  src/Application/GameWindowHandler.cpp
  src/Application/main.cpp
  src/Engine/ErrorHandling.cpp
  src/Engine/Graphics/NuklearEventHandler.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Plugins/EngineController.cpp
  src/Engine/Plugins/EngineTracePlugin.cpp
  src/Engine/Plugins/EngineTracer.cpp
  src/Library/Logger/Logger.cpp
  src/Library/Trace/EventTrace.cpp
  src/Library/Trace/PaintEvent.h
  src/Media/MediaLogger.cpp
  src/Platform/Filters/FilteringEventHandler.cpp
  src/Platform/Filters/FilteringEventHandler.h
  src/Platform/Filters/PlatformEventFilter.cpp
  src/Platform/Filters/PlatformEventFilter.h
  src/Platform/Platform.h
  src/Platform/PlatformEnums.h
  src/Platform/PlatformEventHandler.cpp
  src/Platform/PlatformEventLoop.h
  src/Platform/PlatformEvents.h
  src/Platform/PlatformLogger.h
  src/Platform/PlatformWindow.h
  src/Platform/Proxy/ProxyPlatform.cpp
  src/Platform/Proxy/ProxyPlatform.h
  src/Platform/Sdl/SdlEnumTranslation.cpp
  src/Platform/Sdl/SdlEventLoop.cpp
  src/Platform/Sdl/SdlLogger.cpp
  src/Platform/Sdl/SdlPlatform.cpp
  src/Platform/Sdl/SdlPlatform.h
  src/Platform/Sdl/SdlPlatformSharedState.cpp
  src/Platform/Win/WinPlatform.cpp
  test/Bin/GameTest/GameTestMain.cpp
Labels: 🥺Ready for Review

#404 Bugfixes
  src/Engine/Graphics/Camera.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/ItemTable.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#410 issue391
  CMakeModules/Git.cmake
Labels: 👍Approved

#409 work on todos
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameOver.cpp
  src/Arcomage/Arcomage.cpp
  src/Arcomage/Arcomage.h
  src/Engine/AssetsManager.h
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Camera.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/IRenderFactory.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/LightmapBuilder.h
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/GLShaderLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Viewport.h
  src/Engine/IocContainer.cpp
  src/Engine/IocContainer.h
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Tables/IconFrameTable.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
  src/Utility/Color.h
Labels: 👍👍Very Approved

#419 Testing docs
  HACKING.md
Labels: 👍Approved

#421 Updated README.
  README.md
Labels: 👍Approved

#413 Refactor of spells casting function
  src/Application/Game.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
Labels: 👍Approved

#420 fix #408 and add test
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameOver.cpp
  src/Application/GameOver.h
  src/Application/GameWindowHandler.cpp
  src/Engine/AssetsManager.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Party.cpp
  src/GUI/CMakeLists.txt
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIGameOver.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIModal.cpp
  src/GUI/UI/UIModal.h
  src/GUI/UI/UIPartyCreation.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#406 Fix for #402
  src/Application/Game.cpp
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/mm7_data.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#424 Working on TODOs
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/LOD.cpp
  src/Engine/SaveLoad.cpp
  src/Library/Compression/Compression.cpp
  src/Utility/CMakeLists.txt
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
  src/Utility/Memory/FreeDeleter.h
  src/Utility/Streams/InputStream.cpp
  src/Utility/Streams/InputStream.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/CMakeLists.txt
  test/Testing/Game/TestConfig.cpp
  test/Testing/Game/TestConfig.h
  test/Testing/Game/TestController.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#423 fix #417
  src/Engine/Graphics/BspRenderer.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#434 Add info on ENABLE_TESTS to HACKING.
  HACKING.md
Labels: 🥺Ready for Review

#428 Fix #427
  src/Application/Game.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#430 Some cleanup of Spells.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
Labels: ❓Questions

#437 Test for #427 works
  src/Engine/Party.cpp
  src/Engine/Plugins/CMakeLists.txt
  src/Engine/Plugins/EngineController.cpp
  src/Engine/Plugins/EngineTracePlaybackFlags.h
  src/Engine/Plugins/EngineTracer.cpp
  src/Engine/Plugins/EngineTracer.h
  test/Bin/GameTest/CMakeLists.txt
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#438 Some cleanup in spells after merging the latest PR
  src/Application/Game.cpp
  src/Engine/Events.cpp
  src/Engine/IocContainer.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
Labels: 👍Approved

#439 Cleanup
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Vis.cpp
  src/Library/Serialization/EnumSerializer.cpp
  src/Library/Serialization/Tests/Serialization_ut.cpp
  src/Utility/Geometry/BBox.h
Labels: 🥺Ready for Review

#429 Refactor spells duration calculation
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Time.h
Labels: ❓Questions

#433 Docs improvement
  HACKING.md
  README.md
Labels: 🥺Ready for Review

#446 Docs updated after merge
  HACKING.md
  README.md
Labels: 👍Approved

#443 Resolved some gamepad-related TODOs in Platform code
  src/Application/GameKeyboardController.cpp
  src/Application/GameKeyboardController.h
  src/Application/GameWindowHandler.cpp
  src/Application/GameWindowHandler.h
  src/Library/Application/PlatformApplication.h
  src/Library/Trace/EventTrace.cpp
  src/Platform/Filters/PlatformEventFilter.cpp
  src/Platform/Filters/PlatformEventFilter.h
  src/Platform/Platform.h
  src/Platform/PlatformEnums.h
  src/Platform/PlatformEventHandler.cpp
  src/Platform/PlatformEventHandler.h
  src/Platform/PlatformEvents.h
  src/Platform/PlatformGamepad.h
  src/Platform/Proxy/ProxyGamepad.cpp
  src/Platform/Proxy/ProxyGamepad.h
  src/Platform/Proxy/ProxyPlatform.cpp
  src/Platform/Proxy/ProxyPlatform.h
  src/Platform/Sdl/SdlEnumTranslation.cpp
  src/Platform/Sdl/SdlEnumTranslation.h
  src/Platform/Sdl/SdlEventLoop.cpp
  src/Platform/Sdl/SdlEventLoop.h
  src/Platform/Sdl/SdlGamepad.cpp
  src/Platform/Sdl/SdlGamepad.h
  src/Platform/Sdl/SdlPlatform.cpp
  src/Platform/Sdl/SdlPlatform.h
  src/Platform/Sdl/SdlPlatformSharedState.cpp
  src/Platform/Sdl/SdlPlatformSharedState.h
  src/Platform/Sdl/SdlWindow.cpp
  src/Platform/Sdl/SdlWindow.h
Labels: 👍Approved

#436 Fix projectile spell sound too quiet
  src/Application/GameMenu.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/GUI/UI/UIHouses.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Audio/OpenALSoundProvider.cpp
Labels: 👍Approved

#450 Added test for #203
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#452 Minor fixes and a few tests
  src/Engine/Engine.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#449 Test for #163
  src/Engine/Plugins/EngineController.cpp
  src/Engine/SaveLoad.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIProgressBar.h
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#455 Update HACKING
  HACKING.md
Labels: 🥺Ready for Review

#447 Spells refactor, 2nd iteration
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/GUI/GUIWindow.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/Io/KeyboardInputHandler.cpp
Labels: 👍👍Very Approved

#468 Delete TODO.md
  TODO.md
Labels: 👍Approved

#459 Spells refactor, 3rd iteration
  src/Application/Game.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
Labels: ❓Questions

#456 Clean up UpdateActors_ODM w/o changing semantic
  src/Engine/Graphics/Outdoor.cpp
Labels: 👍Approved

#457 Dropped redraw flags
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameWindowHandler.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Overlays.h
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Viewport.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIShops.cpp
Labels: 👍Approved

#469 Fix trip on assert for accessing spell school with SPELL_NONE
  src/Io/KeyboardInputHandler.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#474 Using ints in RandomEngine
  HACKING.md
  src/Library/Random/MersenneTwisterRandomEngine.h
  src/Library/Random/NonRandomEngine.h
  src/Library/Random/Random.h
  src/Library/Random/RandomEngine.h
Labels: 🥺Ready for Review

#472 Spells refactor, 4th iteration
  src/Application/Game.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/SpellFxRenderer.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/Time.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/CMakeLists.txt
  src/GUI/GUIEnums.cpp
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#475 Use fmt for logging
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/GLShaderLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/LOD.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Plugins/EngineTracer.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Tables/TileTable.cpp
  src/Engine/mm7text_ru.cpp
  src/GUI/GUIWindow.cpp
  src/Library/Logger/CMakeLists.txt
  src/Library/Logger/Logger.cpp
  src/Library/Logger/Logger.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/MediaPlayer.cpp
  test/Tests/CMakeLists.txt
Labels: 👍Approved
