Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-03, with the labels that each got.

#473 Small refactor of ParticleEngine, fixes #453
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/ParticleEngine.cpp
  src/Engine/Graphics/ParticleEngine.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/SpellFxRenderer.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Utility/Color.h
Labels: ❓Questions

#480 Added test for #293
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 🥺Ready for Review

#477 More logger fixes
  src/Application/Game.cpp
  src/Application/GamePathResolver.cpp
  src/Engine/Graphics/HWLContainer.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Vis.cpp
  src/GUI/GUIWindow.cpp
Labels: 🥺Ready for Review

#479 Make #331 assert in debug
  src/Engine/Objects/ObjectList.cpp
  src/Engine/Objects/ObjectList.h
Labels: 🥺Ready for Review

#476 Fix #331
  src/Engine/Objects/SpriteObject.cpp
  src/GUI/UI/UIHouses.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#481 Some cleanup in Utility
  src/Application/Game.cpp
  src/Application/GameOver.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIShops.cpp
  src/Library/Application/PlatformApplication.cpp
  src/Library/Config/Config.cpp
  src/Library/Config/ConfigSection.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Platform/Filters/FilteringEventHandler.cpp
  src/Platform/Sdl/SdlPlatformSharedState.cpp
  src/Utility/MapAccess.h
  src/Utility/Reversed.h
  src/Utility/Segment.h
  src/Utility/String.cpp
  src/Utility/String.h
Labels: 👍Approved

#485 More codestyle in Utility
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/HWLContainer.cpp
  src/Engine/Localization.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Tables/StorylineTextTable.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/Library/Serialization/EnumSerializer.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Utility/DataPath.cpp
  src/Utility/Embedded.h
  src/Utility/FileSystem.cpp
  src/Utility/FileSystem.h
  src/Utility/Flags.h
  src/Utility/IndexedArray.h
  src/Utility/ScopeGuard.h
  src/Utility/Segment.h
  src/Utility/String.cpp
  src/Utility/String.h
Labels: 🥺Ready for Review

#484 Fix experience gain when learning skill is not present
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#486 Fix Water Walk and Fly mana draining
  src/Application/GameConfig.h
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/Time.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
Labels: ❓Questions

#497 Tests for #293
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#499 Some cleanup in collisions code
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/Outdoor.cpp
  src/Utility/Geometry/Plane.h
Labels: 👍Approved

#482 Add -Werror=unused-result
  CMakeLists.txt
  src/Engine/Graphics/HWLContainer.cpp
  src/Engine/Graphics/HWLContainer.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/LOD.cpp
  src/Library/Lod/LodReader.cpp
  src/Media/MediaPlayer.cpp
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
Labels: 👍Approved

#494 Fix #490
  src/Engine/Spells/CastSpellInfo.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#495 Fix #491
  src/Engine/Spells/CastSpellInfo.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#505 Support exiting test from targeted spell casting state
  src/Engine/Plugins/EngineController.cpp
Labels: 👍Approved

#508 Revert #499
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/Outdoor.cpp
  src/Utility/Geometry/Plane.h
Labels: 👍Approved

#507 Rename and enable actually swapping event queues
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#511 Fix speech/animation of active character on scripted interactions
  CMakeLists.txt
  src/Engine/Events.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#510 Refactor Lloyd Beacon, Town Portal and fix cast spells from scrolls
  src/Application/Game.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Spellbook.cpp
  src/Library/Random/RandomEngine.h
  src/Media/Audio/AudioPlayer.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#523 Getting rid of pPlayers array, step 1
  src/Application/Game.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObjectType.h
  src/Engine/Party.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/mm7_data.h
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UIShops.cpp
Labels: 🥺Ready for Review

#501 Outdoor movement fixes
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIStatusBar.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/KeyboardInputHandler.h
  src/Media/Audio/AudioPlayer.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#525 Change method of access to actors in viewport, method 3
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
Labels: 👍Approved

#529 Getting rid of pPlayers array, step 2
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/GUI/GUIWindow.cpp
Labels: 🥺Ready for Review

#524 Refactor targeted spell UI
  src/Application/Game.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/GUI/CMakeLists.txt
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UISpell.cpp
  src/GUI/UI/UISpell.h
  src/Io/Mouse.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#530 Fix Disease spell and mana drain for some buff spells
  src/Engine/Spells/CastSpellInfo.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#533 Blob::Read handles zero-sized reads correctly
  src/Utility/Memory/Blob.cpp
Labels: 👍Approved, 🥺Ready for Review

#537 Update cpplint
  CMakeModules/CppLint.cmake
Labels: 👍Approved

#536 Codestyle in Blob
  src/Engine/Graphics/HWLContainer.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/LOD.cpp
  src/Engine/SaveLoad.cpp
  src/Library/Compression/Compression.cpp
  src/Library/Lod/LodReader.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/MediaPlayer.cpp
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
Labels: 👍Approved

#535 Refactor spell impact processing function
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Objects/SpriteObjectType.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Utility/Math/TrigLut.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: ❓Questions

#532 move uActiveCharacter to party
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
Labels: 🥺Ready for Review

#539 Codestyle in Color
  src/Arcomage/Arcomage.cpp
  src/Engine/AssetsManager.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Weather.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/SpellFxRenderer.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIShops.cpp
  src/Utility/Color.h
Labels: 👍Approved

#538 Refactor AOE attacks processing and structure
  src/Application/GameConfig.h
  src/Engine/AttackList.cpp
  src/Engine/AttackList.h
  src/Engine/CMakeLists.txt
  src/Engine/Engine.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/Engine/mm7_data.cpp
  src/Engine/stru298.cpp
  src/Engine/stru298.h
Labels: 👍Approved

#544 More codestyle in Utility
  src/Application/Game.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Serialization/Deserializer.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/Serializer.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Utility/DataPath.cpp
  src/Utility/DataPath.h
  src/Utility/Exception.h
  src/Utility/FileSystem.cpp
  src/Utility/Geometry/Plane.h
  src/Utility/Geometry/Rect.h
  src/Utility/Geometry/Size.h
  src/Utility/Geometry/Vec.h
  src/Utility/Math/Float.h
  src/Utility/Math/Tests/Float_ut.cpp
  src/Utility/Math/TrigLut.cpp
  src/Utility/Math/TrigLut.h
  src/Utility/Memory/Blob.cpp
  src/Utility/Streams/FileInputStream.cpp
  src/Utility/Streams/FileInputStream.h
  src/Utility/Streams/FileOutputStream.cpp
  src/Utility/Streams/FileOutputStream.h
  src/Utility/Streams/InputStream.cpp
  src/Utility/Streams/InputStream.h
  src/Utility/Streams/MemoryInputStream.cpp
  src/Utility/Streams/MemoryInputStream.h
  src/Utility/Streams/OutputStream.h
  src/Utility/Streams/StringOutputStream.cpp
  src/Utility/Streams/StringOutputStream.h
  src/Utility/Streams/Tests/FileOutputStream_ut.cpp
  src/Utility/String.cpp
  src/Utility/Workaround/ToUnderlying.h
  test/Bin/GameTest/GameTestMain.cpp
Labels: 👍Approved

#541 Fix targeting issues for some spells
  src/Application/Game.cpp
  src/Application/GameConfig.h
  src/Engine/Spells/CastSpellInfo.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#547 Refactor AI_SpellAttack function
  src/Engine/Objects/Actor.cpp
  src/Engine/Time.h
Labels: 👍Approved

#548 Resolve warnings in Sprites.cpp
  src/Engine/Graphics/Sprites.cpp
Labels: 👍Approved

#543 Cleanup
  src/Application/Game.cpp
  src/Application/GameConfig.h
  src/Application/GameMenu.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/mm7_data.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIStatusBar.cpp
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#549 Random refactoring
  src/Engine/Events.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/ObjectList.cpp
  src/Engine/Objects/ObjectList.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Spells/CMakeLists.txt
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/SpellEnums.h
  src/Engine/Spells/Spells.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIPopup.cpp
Labels: ❓Questions

#545 Cleanup
  src/Application/GameOver.cpp
  src/Engine/Events.cpp
  src/Engine/IocContainer.cpp
  src/Engine/Localization.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/CMakeLists.txt
  src/GUI/GUIBountyHunting.cpp
  src/GUI/GUIBountyHunting.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/Utility/Format.h
  src/Utility/String.cpp
  src/Utility/String.h
Labels: 🥺Ready for Review

#550 fix exception
  src/Engine/Spells/CastSpellInfo.cpp
Labels: ❓Questions

#551 use yaw and pitch for rotation naming
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Camera.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Level/Decoration.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Utility/Geometry/Vec.h
Labels: 👍Approved

#553 Separate API for playing UI sounds
  src/Application/Game.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UIShops.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
Labels: 👍Approved

#552 Refactor UpdateObject_fn0_ODM
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Utility/Geometry/Vec.h
Labels: 👍Approved

#556 test for #248
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestPartyCreationMenu.cpp
Labels: 👍Approved

#554 Some refactoring related to character facial expressions
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Party.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIGame.cpp
Labels: ❓Questions

#559 Rename PlaySound method of Player to playReaction
  src/Application/Game.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
Labels: 👍Approved

#560 Renamings
  src/Application/CMakeLists.txt
  src/Application/Game.cpp
  src/Application/GameTraceHandler.cpp
  src/Engine/CMakeLists.txt
  src/Engine/Components/CMakeLists.txt
  src/Engine/Components/EngineControlComponent.cpp
  src/Engine/Components/EngineControlComponent.h
  src/Engine/Components/EngineControlState.h
  src/Engine/Components/EngineControlStateHandle.h
  src/Engine/Components/EngineController.cpp
  src/Engine/Components/EngineController.h
  src/Engine/Components/EngineDeterministicComponent.cpp
  src/Engine/Components/EngineDeterministicComponent.h
  src/Engine/Components/EngineTraceComponent.cpp
  src/Engine/Components/EngineTraceComponent.h
  src/Engine/Components/EngineTracePlaybackFlags.h
  src/Engine/Components/EngineTracer.cpp
  src/Engine/Components/EngineTracer.h
  src/Engine/Plugins/CMakeLists.txt
  src/Library/Application/PlatformApplication.cpp
  src/Library/Application/PlatformApplication.h
  src/Library/Application/PlatformApplicationAware.h
  src/Library/Application/PlatformIntrospection.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/GameTest.cpp
  test/Testing/Game/GameTest.h
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
Labels: 👍Approved

#557 Refactor function UpdateObject_fn0_BLV
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
Labels: 👍Approved

#555 pcx cleanup
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/PCX.cpp
  src/Engine/Graphics/PCX.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/SaveLoad.cpp
Labels: 👍Approved

#561 Fix log format in MediaLogger
  src/Media/MediaLogger.cpp
Labels: 👍Approved

#564 Introduce item types functions
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/Player.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#565 cmake files cleanup, consistent library naming
  CMakeLists.txt
  src/Application/CMakeLists.txt
  src/Arcomage/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/Engine/Components/CMakeLists.txt
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Serialization/CMakeLists.txt
  src/Engine/Spells/CMakeLists.txt
  src/Engine/Tables/CMakeLists.txt
  src/Engine/TurnEngine/CMakeLists.txt
  src/GUI/CMakeLists.txt
  src/Io/CMakeLists.txt
  src/Library/Application/CMakeLists.txt
  src/Library/Compression/CMakeLists.txt
  src/Library/Config/CMakeLists.txt
  src/Library/Json/CMakeLists.txt
  src/Library/Lod/CMakeLists.txt
  src/Library/Logger/CMakeLists.txt
  src/Library/Random/CMakeLists.txt
  src/Library/Serialization/CMakeLists.txt
  src/Library/Trace/CMakeLists.txt
  src/Media/CMakeLists.txt
  src/Platform/CMakeLists.txt
  src/Utility/CMakeLists.txt
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/UnitTest/CMakeLists.txt
  test/Testing/Extensions/CMakeLists.txt
  test/Testing/Game/CMakeLists.txt
  test/Testing/Unit/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: 👍Approved

#566 Style renaming PlaySound in Arcomage
  src/Arcomage/Arcomage.cpp
  src/Arcomage/Arcomage.h
Labels: 👍Approved

#562 Replace more PlaySound with specialized API calls
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UIHouses.cpp
  src/Io/Mouse.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
Labels: 👍Approved

#568 Splitting up components into sublibraries
  src/Application/CMakeLists.txt
  src/Application/Game.cpp
  src/Application/GameTraceHandler.cpp
  src/Engine/Components/CMakeLists.txt
  src/Engine/Components/Control/CMakeLists.txt
  src/Engine/Components/Control/EngineControlComponent.cpp
  src/Engine/Components/Control/EngineControlComponent.h
  src/Engine/Components/Control/EngineControlState.h
  src/Engine/Components/Control/EngineControlStateHandle.h
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Components/Control/EngineController.h
  src/Engine/Components/Deterministic/CMakeLists.txt
  src/Engine/Components/Deterministic/EngineDeterministicComponent.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.h
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Components/Trace/EngineTraceComponent.cpp
  src/Engine/Components/Trace/EngineTraceComponent.h
  src/Engine/Components/Trace/EngineTracePlaybackFlags.h
  src/Engine/Components/Trace/EngineTracer.cpp
  src/Engine/Components/Trace/EngineTracer.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/GameTest.cpp
  test/Testing/Game/GameTest.h
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
Labels: 👍Approved

#567 Get rid of some hardcoded players number and clean up wetsuit related code
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIShops.cpp
Labels: ❓Questions

#569 Some cleanup in game tests
  test/Tests/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#570 Preparing to turn SPELL_TYPE into an enum class
  src/Application/Game.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Spells/SpellEnums.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
Labels: 👍Approved

#577 Split EngineTracer into two independent classes
  src/Application/Game.cpp
  src/Application/GameTraceHandler.cpp
  src/Application/GameTraceHandler.h
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.h
  src/Engine/Components/Trace/EngineTracer.cpp
  src/Engine/Components/Trace/EngineTracer.h
  test/Testing/Game/TestController.cpp
Labels: 👍Approved

#575 _activeCharacter private with getter/setter
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#588 Using PlayerConditions::HasAll/HasNone where appropriate
  src/Engine/Engine.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Party.cpp
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#580 Refactor use item function
  src/Engine/IocContainer.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#590 Style renaming PlaySound of Actor
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
Labels: 👍Approved

#593 Move some globals and code related to lloyd's beacon and town portal spells
  src/Application/Game.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/LloydsBook.h
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Books/TownPortalBook.h
Labels: 👍Approved

#596 Codestyle in Library/Config
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GameMenu.cpp
  src/Application/GameOptions.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/AttackList.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Conditions.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/IRenderFactory.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Graphics/Weather.cpp
  src/Engine/LOD.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/Io/KeyboardActionMapping.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Library/Config/AbstractConfigValue.h
  src/Library/Config/Config.cpp
  src/Library/Config/Config.h
  src/Library/Config/ConfigSection.cpp
  src/Library/Config/ConfigSection.h
  src/Library/Config/ConfigValue.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/MediaLogger.cpp
  src/Media/MediaPlayer.cpp
  test/Testing/Game/TestConfig.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#599 Saner Library/Config implementation
  src/Application/GameConfig.h
  src/Application/GameOptions.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/RenderBase.cpp
  src/Io/KeyboardActionMapping.cpp
  src/Library/Config/AbstractConfigValue.h
  src/Library/Config/AnyConfigEntry.cpp
  src/Library/Config/AnyConfigEntry.h
  src/Library/Config/AnySerializer.h
  src/Library/Config/CMakeLists.txt
  src/Library/Config/Config.cpp
  src/Library/Config/Config.h
  src/Library/Config/ConfigEntry.h
  src/Library/Config/ConfigFwd.h
  src/Library/Config/ConfigSection.cpp
  src/Library/Config/ConfigSection.h
  src/Library/Config/ConfigValue.h
Labels: 🥺Ready for Review
