Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-06, with the labels that each got.

#904 Refactor houses UI: Transport
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/Houses/Transport.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved, 🥺Ready for Review

#905 Move town hall functions to separate file
  src/GUI/CMakeLists.txt
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Houses/CMakeLists.txt
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/TownHall.h
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#907 Numpad and tests
  src/Application/GameWindowHandler.cpp
  src/Platform/Sdl/SdlEnumTranslation.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍👍Very Approved

#911 Move shops UI to Houses module
  src/Application/Game.cpp
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/Houses/CMakeLists.txt
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIPopup.cpp
Labels: 👍👍Very Approved

#909 Refactor Jail and Mercenary Guild
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Houses/Jail.cpp
  src/GUI/UI/Houses/Jail.h
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍👍Very Approved

#913 Move NPCStats class and related types to Tables module
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/NPCTable.cpp
  src/Engine/Tables/NPCTable.h
  src/Engine/mm7_data.cpp
Labels: 👍👍Very Approved

#914 Remove indentation level from game message queue processing
  src/Application/Game.cpp
Labels: 👍👍Very Approved

#915 fix 906
  src/Application/GameConfig.h
  src/Engine/Conditions.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.h
  src/Engine/Spells/Spells.h
  src/Engine/Time.h
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/Media/Audio/AudioPlayer.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved, 🥺Ready for Review

#917 Remove some more global text table buffers
  src/Application/Game.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/Tables/FactionTable.cpp
  src/Engine/Tables/FactionTable.h
  src/Engine/Tables/ItemTable.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIQuickReference.cpp
Labels: 👍Approved

#910 Refactor houses UI: Town Hall
  src/Engine/Time.h
  src/GUI/GUIDialogues.h
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/TownHall.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍👍Very Approved

#918 Refactor houses UI: Shops
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#919 Using class Color to store palette in GraphicsImage
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/TextureOpenGL.cpp
Labels: 👍Approved

#921 Add test #832 #774 #742 #651
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#922 button transparency
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UISaveLoad.cpp
Labels: 👍Approved, 🥺Ready for Review

#924 Broken up Engine/Graphics/Image.h/cpp into several files
  src/Engine/Engine.cpp
  src/Engine/GameResourceManager.cpp
  src/Engine/Graphics/BSPModel.cpp
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Graphics/TextureFrameTable.h
  src/Engine/Graphics/Texture_MM7.cpp
  src/Engine/Graphics/Texture_MM7.h
  src/Engine/LOD.h
  src/Engine/Serialization/LegacyImages.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIGame.h
Labels: 🥺Ready for Review

#925 Renamings in GraphicsImage, added GraphicsImage::size
  src/Arcomage/Arcomage.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/TextureOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/SaveLoad.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UISpell.cpp
  src/GUI/UI/UISpellbook.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#927 snake case PlatformKey
  src/Application/GameConfig.h
  src/Application/GameKeyboardController.cpp
  src/Application/GameKeyboardController.h
  src/Application/GameTraceHandler.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/NuklearEventHandler.cpp
  src/GUI/GUIWindow.cpp
  src/Io/Key.cpp
  src/Io/KeyboardActionMapping.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/KeyboardInputHandler.h
  src/Io/Mouse.cpp
  src/Platform/PlatformEnums.h
  src/Platform/Sdl/SdlEnumTranslation.cpp
  src/Platform/Sdl/SdlEventLoop.cpp
  test/Tests/TestIssues.cpp
Labels: 👍👍Very Approved

#928 Propagating Image use
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/OpenGL/TextureOpenGL.cpp
  src/Engine/Graphics/OpenGL/TextureOpenGL.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Objects/Player.cpp
  src/Library/Image/ImageFunctions.cpp
  src/Library/Image/ImageFunctions.h
  src/Library/Image/PCX.cpp
  src/Library/Image/PCX.h
  src/Media/MediaPlayer.cpp
Labels: 👍👍Very Approved, 🥺Ready for Review

#931 Minor cleanup and todos
  src/Engine/Localization.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Party.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/Library/Color/ColorTable.h
  test/Tests/TestIssues.cpp
Labels: 👍👍Very Approved

#933 Some cleanup of GUIWindow files
  src/Engine/Engine.cpp
  src/Engine/Objects/Player.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIMessageScroll.cpp
  src/GUI/UI/UIMessageScroll.h
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIPopup.h
Labels: 👍Approved

#932 Remove intermediate strings from NPC table
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Tables/NPCTable.cpp
  src/Engine/Tables/NPCTable.h
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#935 Style renaming different enums
  src/Application/Game.cpp
  src/Engine/Events/EventEnums.h
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/EventInterpreter.h
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/LocationEnums.h
  src/Engine/Graphics/LocationFunctions.cpp
  src/Engine/Graphics/LocationFunctions.h
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Chest.h
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/Items.h
  src/Engine/Objects/NPCEnums.h
  src/Engine/Objects/ObjectList.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Objects/SpriteObjectType.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Tables/MerchantTable.cpp
  src/Engine/TurnEngine/TurnEngine.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UIBooks.h
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UIRest.h
Labels: 🥺Ready for Review

#936 Allow some control of books from keyboard
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
Labels: 🥺Ready for Review

#940 Resolving TODOs
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameIocContainer.cpp
  src/Application/GameIocContainer.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Localization.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Party.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/SpellEnums.h
  src/Engine/Tables/ItemTable.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UISpellbook.cpp
Labels: 👍Approved

#937 Cleaning up UIQuickReference
  src/GUI/UI/UIQuickReference.cpp
Labels: 👍Approved

#938 Make items without a value are sellable for 1 gold
  src/Engine/PriceCalculator.cpp
Labels: 👍Approved

#944 Propagating Color usage
  src/Engine/Engine.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Camera.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/ParticleEngine.cpp
  src/Engine/Graphics/ParticleEngine.h
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/SpellFxRenderer.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Library/Color/Color.h
Labels: 👍Approved

#943 House UI: refactor more functions related to picking dialogue options
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIButton.cpp
  src/GUI/GUIButton.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Tavern.h
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Temple.h
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Training.h
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#951 Additional refactory changes in Books UI
  src/Application/Game.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UIBooks.h
Labels: 🥺Ready for Review

#950 Refactor shop screen click
  src/Application/Game.cpp
  src/Engine/Objects/NPC.cpp
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MagicGuild.h
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: ❓Questions

#949 Unify skills training dialogue
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Tavern.h
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Temple.h
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Training.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#953 Refactor house sound functions
  src/Application/Game.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UITransition.cpp
Labels: 👍Approved

#954 Propagating Color usage p2
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/IRenderFactory.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/LightmapBuilder.cpp
  src/Engine/Graphics/LightmapBuilder.h
  src/Engine/Graphics/LightsStack.cpp
  src/Engine/Graphics/LightsStack.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/PaletteManager.h
  src/Engine/Graphics/ParticleEngine.cpp
  src/Engine/Graphics/ParticleEngine.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Objects/ObjectList.cpp
  src/Engine/Objects/ObjectList.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/SpellFxRenderer.cpp
  src/GUI/GUIFont.cpp
  src/Library/Color/CMakeLists.txt
  src/Library/Color/Color.h
  src/Library/Color/Colorf.cpp
  src/Library/Color/Colorf.h
  src/Library/Color/HsvColorf.cpp
  src/Library/Color/HsvColorf.h
Labels: 👍Approved

#956 Cleaning up DrawText
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/GUI/GUIButton.cpp
  src/GUI/GUIButton.h
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIMessageScroll.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UIStatusBar.cpp
Labels: 🥺Ready for Review

#957 Dropped class Texture
  src/Arcomage/Arcomage.h
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Graphics/BSPModel.cpp
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/OpenGL/TextureOpenGL.cpp
  src/Engine/Graphics/OpenGL/TextureOpenGL.h
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/ParticleEngine.h
  src/Engine/Graphics/Polygon.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Graphics/Sprites.h
  src/Engine/Graphics/Texture.h
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Graphics/TextureFrameTable.h
  src/Engine/Objects/Player.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/SpellFxRenderer.h
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/IconFrameTable.h
  src/Engine/Tables/TileFrameTable.h
  src/GUI/GUIFont.h
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICharacter.h
  src/GUI/UI/UICredits.h
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIPopup.h
  src/Library/Color/ColorTable.h
  src/Media/MediaPlayer.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#960 More Color fixes
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/GUI/GUIButton.h
  src/GUI/GUIFont.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 🥺Ready for Review

#958 LegacyImages functions naming: snapshot/reconstruct
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Serialization/CommonImages.h
  src/Engine/Serialization/CompositeImages.cpp
  src/Engine/Serialization/CompositeImages.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/Serialization/MultiStageSerialization.h
  src/GUI/GUIFont.cpp
  src/Library/Binary/BlobSerialization.h
Labels: 🥺Ready for Review

#968 Dropped some of the IDA remnants
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/MM7.h
  src/Engine/Party.h
  src/GUI/GUIWindow.cpp
Labels: 👍Approved

#963 Renamings in Engine/Serialization
  src/Engine/CMakeLists.txt
  src/Engine/EngineIocContainer.cpp
  src/Engine/Graphics/DecorationList.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/ObjectList.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/CMakeLists.txt
  src/Engine/Snapshots/CommonSnapshots.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Snapshots/SnapshotSerialization.h
  src/Engine/SpawnPoint.h
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/PlayerFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/GUI/GUIFont.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Library/Random/Random.h
  src/Media/Audio/AudioPlayer.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#961 Work on textures continued
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Engine/Graphics/OpenGL/TextureOpenGL.cpp
  src/Engine/Graphics/OpenGL/TextureOpenGL.h
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Graphics/TextureRenderId.h
  src/GUI/GUIFont.cpp
Labels: 🥺Ready for Review

#969 Resolved TODOs with snapshot includes
  src/Engine/Graphics/DecorationList.cpp
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/ObjectList.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/PlayerFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Media/Audio/AudioPlayer.cpp
Labels: 👍Approved

#972 Virtualize playHouseGoodbyeSpeech
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/Houses/Bank.h
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Temple.h
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#975 Rename BuildingType enum values
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/PriceCalculator.cpp
  src/Engine/Tables/BuildingTable.cpp
  src/Engine/Tables/BuildingTable.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIPopup.cpp
Labels: 🥺Ready for Review

#967 Set colors explicitry, drop special processing of Color()
  src/Arcomage/Arcomage.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIMessageScroll.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/GUI/UI/UITransition.cpp
  src/Library/Color/Color.h
Labels: 👍Approved

#962 Cleanup and todos
  src/Application/GameConfig.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Localization.cpp
  src/Engine/Objects/CombinedSkillValue.cpp
  src/Engine/Objects/CombinedSkillValue.h
  src/Engine/Objects/ItemEnchantment.h
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/Library/Color/ColorTable.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/Audio/OpenALSoundProvider.h
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#974 Use vector for house NPC portraits
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#977 update git tag
  test/Bin/GameTest/CMakeLists.txt
Labels: 🥺Ready for Review

#976 More cleanup in snapshots
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/Level/Decoration.h
  src/Engine/Graphics/Overlays.cpp
  src/Engine/Graphics/Overlays.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/ObjectList.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Tables/BuildingTable.h
  src/Engine/Tables/IconFrameTable.h
  src/Engine/Time.h
  src/Engine/mm7_data.h
  src/GUI/GUIFont.h
  src/GUI/UI/UIPartyCreation.cpp
Labels: 👍Approved

#978 Todos
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/LocationFunctions.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/SaveLoad.cpp
  src/Media/Audio/AudioPlayer.cpp
Labels: 👍Approved

#980 Added InputStream::readAll, using it in shader loading code
  src/Engine/Graphics/OpenGL/GLShaderLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.h
  src/Utility/Streams/InputStream.cpp
  src/Utility/Streams/InputStream.h
Labels: 🥺Ready for Review

#982 Add tests
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#984 Convert buildingTable to IndexedArray
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/EventMap.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Tables/BuildingTable.cpp
  src/Engine/Tables/BuildingTable.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UITransition.cpp
  src/GUI/UI/UITransition.h
Labels: 👍Approved

#979 Unify globals for interactable objects in houses
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 🥺Ready for Review

#989 issue fixes
  src/Engine/Objects/Chest.cpp
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#985 Move message queue to separate file
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/CMakeLists.txt
  src/GUI/GUIEnums.h
  src/GUI/GUIMessageQueue.cpp
  src/GUI/GUIMessageQueue.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#990 Minor cleanup
  src/Application/Game.cpp
  src/Application/Game.h
  src/Engine/CMakeLists.txt
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/EngineFactory.cpp
  src/Engine/EngineFactory.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Texture_MM7.h
  src/Engine/LOD.cpp
Labels: 👍Approved

#992 fix #830 minimap date time
  src/GUI/GUIWindow.cpp
Labels: 🥺Ready for Review

#994 Cleanup continued
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameIocContainer.cpp
  src/Application/GameIocContainer.h
  src/Application/GameMenu.cpp
  src/Application/GameMenu.h
  src/Application/GameOver.cpp
  src/Application/GamePathResolver.h
  src/Application/GameTraceHandler.cpp
  src/Application/GameWindowHandler.cpp
  src/Application/GameWindowHandler.h
  src/Arcomage/Arcomage.cpp
  src/Engine/AssetsManager.cpp
  src/Engine/AssetsManager.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/RenderBase.h
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/Sprites.h
  src/Engine/Graphics/Vis.cpp
  src/Engine/LOD.cpp
  src/Engine/LOD.h
Labels: 🥺Ready for Review

#993 Contain message queues in one class
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIEnums.h
  src/GUI/GUIMessageQueue.cpp
  src/GUI/GUIMessageQueue.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Houses/Bank.cpp
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#991 Cleaning up dialogue of houses npc
  src/Application/Game.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Time.h
  src/GUI/GUIEnums.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIDialogue.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UITransition.cpp
Labels: 👍Approved

#998 Resolved a retracing-related TODO
  src/Application/GameKeyboardController.h
  src/Application/main.cpp
  src/Engine/Components/Trace/EngineTraceComponent.cpp
  src/Engine/Components/Trace/EngineTraceComponent.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.h
Labels: 👍Approved

#999 Resolved several TODOs
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/Collisions.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/GUI/UI/UIPartyCreation.cpp
  test/Bin/GameTest/CMakeLists.txt
Labels: 🥺Ready for Review

#1000 Preparing to move out party collision processing
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
Labels: 🥺Ready for Review

#1001 Add tests
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Components/Control/EngineController.h
  src/Engine/Objects/Character.cpp
  src/GUI/UI/UIQuickReference.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1007 More cleanup in BLV_ProcessPartyActions, preparing to move out collision code
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIArena.cpp
  src/Utility/Geometry/Vec.h
Labels: 🥺Ready for Review

#1008 Added another test for #735
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1013 Remove flush method from message queue in favor of clear
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/Character.cpp
  src/GUI/GUIMessageQueue.cpp
  src/GUI/GUIMessageQueue.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UICredits.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
Labels: 🥺Ready for Review

#1014 Small changes around houses
  src/Application/Game.cpp
  src/GUI/GUIButton.cpp
  src/GUI/GUIButton.h
  src/GUI/GUIEnums.h
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#1015 Renamings in Actor & Party
  src/Application/Game.cpp
  src/Engine/Components/Trace/EngineTraceStateAccessor.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/Processor.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UITransition.cpp
  src/Media/Audio/AudioPlayer.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#1019 Move lloyd book functionality processing from game loop to book class
  src/Application/Game.cpp
  src/Engine/Engine.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIEnums.h
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/LloydsBook.h
Labels: 🥺Ready for Review

#1021 avoid division by zero when there is no dialogue options.
  src/GUI/UI/UIHouses.cpp
Labels: 🥺Ready for Review

#1023 add test for #1020
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#1025 Move special NPC dialogue code to UIHouses.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#1024 Move relevant code into Town Portal book
  src/Application/Game.cpp
  src/Engine/MapInfo.h
  src/Engine/PartyEnums.h
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/GUI/UI/Books/LloydsBook.h
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Books/TownPortalBook.h
Labels: 👍Approved

#1026 add function for item offsets. Issue 1022.
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/ItemGrid.cpp
  src/GUI/UI/ItemGrid.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
Labels: ❓Questions

#1027 test for starting quests for custom party, issue #742
  test/Tests/TestIssues.cpp
Labels: ❓Questions

#1029 Move NPC dialogue functions into separate file
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/CMakeLists.txt
  src/GUI/UI/NPCTopics.cpp
  src/GUI/UI/NPCTopics.h
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIArena.h
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved
