Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-04, with the labels that each got.

#610 We don't need #pragma comment(lib, "opengl32.lib") on windows
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
Labels: 👍Approved

#609 Codestyle in Library/Logger
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GamePathResolver.cpp
  src/Application/GameWindowHandler.cpp
  src/Application/main.cpp
  src/Engine/AssetsManager.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/ClippingFunctions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/HWLContainer.cpp
  src/Engine/Graphics/IRenderFactory.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/LightsStack.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/OpenGL/GLShaderLoader.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PaletteManager.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Sprites.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/LOD.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/Engine/mm7text_ru.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIPopup.cpp
  src/Library/Logger/Logger.cpp
  src/Library/Logger/Logger.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/MediaLogger.cpp
  src/Media/MediaPlayer.cpp
  test/Bin/GameTest/GameTestMain.cpp
Labels: 👍Approved

#604 Refactor around array of max skill mastery per class
  src/Application/Game.cpp
  src/Engine/Objects/PlayerEnums.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/Utility/Color.h
Labels: ❓Questions

#616 Pack of issues fixes
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/SpellFxRenderer.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#618 Improve tests
  src/Engine/Components/Control/EngineController.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#617 Refactored command line options, handling verbose logging properly
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameConfig.cpp
  src/Application/GameConfig.h
  src/Application/GameOptions.cpp
  src/Application/GameOptions.h
  src/Application/GamePathResolver.cpp
  src/Application/main.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Objects/Chest.cpp
  src/GUI/UI/UIPopup.cpp
  src/Library/Logger/Logger.h
  src/Media/Audio/AudioPlayer.cpp
  src/Media/MediaLogger.cpp
  src/Platform/PlatformLogger.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestMain.cpp
  test/Bin/GameTest/GameTestOptions.cpp
  test/Bin/GameTest/GameTestOptions.h
Labels: 👍Approved

#619 Add tests
  src/Engine/Components/Control/EngineController.cpp
  src/GUI/UI/UIGame.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#621 Fix issues with NPC skills
  src/Application/Game.cpp
  src/Engine/Conditions.h
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Books/TownPortalBook.h
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UISpell.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#628 Random style changes
  src/Application/Game.cpp
  src/Application/GameOver.cpp
  src/Engine/Conditions.cpp
  src/Engine/Conditions.h
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#629 Test mods
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/TestConfig.cpp
Labels: 👍Approved

#630 Can subscribe to changes in config values now, handling log verbosity this way
  src/Application/Game.cpp
  src/Application/main.cpp
  src/Library/Config/AnyConfigEntry.cpp
  src/Library/Config/AnyConfigEntry.h
  src/Library/Config/AnyHandler.h
  src/Library/Config/CMakeLists.txt
  src/Library/Config/ConfigEntry.h
  src/Library/Config/ConfigFwd.h
  test/Testing/Game/TestConfig.cpp
Labels: 👍Approved

#633 Codestyle in class Game
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameFactory.cpp
  src/Application/main.cpp
  test/Bin/GameTest/GameTestMain.cpp
Labels: 🥺Ready for Review

#634 Fix some issues with alchemy
  src/Engine/Objects/ItemEnums.h
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/ItemTable.h
  src/Engine/Objects/Player.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#635 Fixes for background music
  src/Application/GameMenu.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
Labels: 👍Approved

#636 Fix pair of TODOs and a little refactor of partyFindsGold function
  src/Arcomage/Arcomage.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/GUIBountyHunting.cpp
  src/GUI/UI/UIArena.cpp
Labels: 👍Approved

#637 Moved some of the common code to GameStarter
  src/Application/CMakeLists.txt
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameFactory.cpp
  src/Application/GameFactory.h
  src/Application/GameOptions.cpp
  src/Application/GameOptions.h
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Application/GameStarterOptions.h
  src/Application/main.cpp
  test/Bin/GameTest/GameTestMain.cpp
  test/Bin/GameTest/GameTestOptions.cpp
  test/Bin/GameTest/GameTestOptions.h
Labels: 👍Approved

#641 Hotfix when OpenAL failed to create audio sample
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
Labels: 👍Approved

#640 Minor fixes
  src/Application/GameStarter.cpp
  test/Testing/Game/GameTest.cpp
  test/Testing/Game/TestController.cpp
Labels: 👍Approved

#646 Save config changes in traces
  src/Engine/Components/Trace/EngineTraceComponent.cpp
  src/Engine/Components/Trace/EngineTraceComponent.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.h
  src/Library/Trace/EventTrace.cpp
  src/Library/Trace/EventTrace.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#647 Codestyle in MediaLogger
  src/Media/MediaLogger.cpp
  src/Media/MediaLogger.h
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#648 Codestyle in Library/Random
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Components/Deterministic/EngineDeterministicComponent.cpp
  src/Engine/Components/Trace/EngineTraceComponent.cpp
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Level/Decoration.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/ParticleEngine.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Weather.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Tables/PlayerFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIBountyHunting.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/Library/Random/MersenneTwisterRandomEngine.h
  src/Library/Random/NonRandomEngine.h
  src/Library/Random/RandomEngine.cpp
  src/Library/Random/RandomEngine.h
Labels: 👍Approved

#650 door offsets should be signed
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
Labels: 👍Approved

#652 Fix door sounds starting each frame
  src/Media/Audio/AudioPlayer.cpp
Labels: 👍Approved

#653 Retracing
  src/Application/Game.cpp
  src/Application/GameConfig.cpp
  src/Application/GameConfig.h
  src/Application/GameOptions.cpp
  src/Application/GameOptions.h
  src/Application/GameTraceHandler.cpp
  src/Application/GameTraceHandler.h
  src/Application/main.cpp
  src/Engine/Components/Control/EngineControlComponent.cpp
  src/Engine/Components/Control/EngineControlState.h
  src/Engine/Components/Trace/CMakeLists.txt
  src/Engine/Components/Trace/EngineTraceConfigurator.cpp
  src/Engine/Components/Trace/EngineTraceConfigurator.h
  src/Engine/Components/Trace/EngineTracePlaybackFlags.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceRecorder.cpp
  src/Engine/Components/Trace/EngineTraceRecorder.h
  src/Library/Random/MersenneTwisterRandomEngine.h
  src/Library/Random/NonRandomEngine.h
  src/Library/Random/RandomEngine.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/CMakeLists.txt
  test/Testing/Game/TestConfig.cpp
  test/Testing/Game/TestConfig.h
  test/Testing/Game/TestController.cpp
Labels: 👍Approved

#655 Outdoor collision fixes
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/Outdoor.cpp
  src/Utility/Geometry/Vec.h
  test/Bin/GameTest/CMakeLists.txt
Labels: 👍Approved

#654 Issue fixes
  src/Application/GameConfig.cpp
  src/Application/GameMenu.cpp
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/mm7_data.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UISaveLoad.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#658 Don't advance random state each frame when tracing
  src/Application/main.cpp
  src/Engine/Components/Trace/EngineTraceComponent.cpp
  src/Engine/Components/Trace/EngineTracePlaybackFlags.h
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#665 Fix issue 662 + test
  src/Engine/Objects/Items.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#667 Refactor sound pausing
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameOver.cpp
  src/Application/GameWindowHandler.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/Books/QuestBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UIBooks.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISpell.cpp
  src/GUI/UI/UITransition.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/MediaPlayer.cpp
Labels: 👍Approved

#669 Indoor actor collisions work the same as outdoor actor collisions
  src/Engine/Graphics/Collisions.cpp
  src/Library/Trace/EventTrace.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#670 Small refactoring relating to outdoor tiles
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/GUI/UI/UIRest.cpp
Labels: 👍Approved

#666 Implement functionality to retain OpenAL buffers
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/Media.h
Labels: ❓Questions

#671 Issues
  src/Engine/Engine.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#685 Got rid of some of the memcpy calls
  src/Engine/Graphics/Vis.cpp
  src/Engine/LOD.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/NPC.h
  src/Engine/Party.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
Labels: 👍Approved

#684 Resolved a TODO in test for issue 417
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#686 Properly clear structs in ctor in Library/Lod
  src/Library/Lod/Internal/LodDirectoryHeader.h
  src/Library/Lod/Internal/LodFileHeader.h
  src/Library/Lod/Internal/LodHeader.h
Labels: 👍Approved

#687 Cleanup in actor collisions code
  src/Engine/Graphics/Collisions.cpp
Labels: 👍Approved

#683 Price calculation refactoring part 1
  src/Engine/CMakeLists.txt
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/ItemTable.h
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/PriceCalculator.cpp
  src/Engine/PriceCalculator.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIShops.cpp
Labels: 👍Approved

#688 Cleanup
  src/Application/GameMenu.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/EngineIocContainer.cpp
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/BspRenderer.h
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Camera.h
  src/Engine/Graphics/ClippingFunctions.cpp
  src/Engine/Graphics/ClippingFunctions.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/IRender.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/Level/Decoration.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/stru314.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UISaveLoad.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/KeyboardInputHandler.h
Labels: 👍Approved

#695 Fix #694 & test for #626
  src/Engine/Components/Control/EngineController.cpp
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#696 Minor cleanup around saveload global state
  src/Engine/SaveLoad.cpp
  src/Engine/SaveLoad.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
Labels: 👍Approved

#692 Fix #689 and #691
  src/Application/Game.cpp
  src/GUI/UI/UISaveLoad.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#690 Fix issue 675 (I hope) and some refactoring/style changes
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/ItemEnchantment.h
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/ItemTable.h
  src/Engine/Objects/Items.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#705 Human-readable exceptions in trace loading.
  src/Library/Trace/EventTrace.cpp
  src/Utility/Streams/FileInputStream.h
  src/Utility/Streams/FileOutputStream.h
  src/Utility/Streams/OutputStream.h
Labels: 👍Approved

#697 Cleaned up LegacyImages & related code
  src/Engine/Objects/Actor.h
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/GUI/GUIFont.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/Utility/IndexedArray.h
  src/Utility/Segment.h
Labels: 👍Approved

#698 Add test for #675
  src/Engine/Objects/Items.h
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#706 Resolved several TODOs in collision handling code & retraced
  src/Engine/Graphics/Collisions.cpp
  test/Bin/GameTest/CMakeLists.txt
Labels: 👍Approved

#712 Update HACKING
  HACKING.md
Labels: 👍Approved

#708 Make corrections for walking sounds
  src/Engine/Engine.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
Labels: 👍Approved

#709 Reset player emotions when entering game menu
  src/Application/GameMenu.cpp
  src/Engine/Engine.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/PlayerEnums.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/GUI/GUIProgressBar.cpp
Labels: 👍Approved

#699 Initial implementation of new event processor
  src/Engine/CMakeLists.txt
  src/Engine/Engine.h
  src/Engine/Events.cpp
  src/Engine/Events.h
  src/Engine/Events/CMakeLists.txt
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/EventMap.cpp
  src/Engine/Events/EventMap.h
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/PlayerEnums.h
Labels: 👍Approved

#718 Changes around branchless dialogue
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Events.cpp
  src/Engine/Events.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIDialogue.h
  src/GUI/UI/UIMainMenu.cpp
  src/Io/Mouse.cpp
Labels: 👍Approved

#721 Renames in Party struct
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Party.h
  src/Engine/SaveLoad.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  test/Tests/TestIssues.cpp
Labels: 🥺Ready for Review

#719 Partial implementation of event processor
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/EventMap.cpp
  src/Engine/Events/EventMap.h
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: 👍Approved

#723 Introduce active character returning method
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIInventory.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/GUI/UI/UITransition.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
Labels: 👍Approved

#722 Allow looting and item picking with no active character
  src/Application/Game.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIHouses.cpp
Labels: 👍Approved

#726 Cleaning up legacyimages
  src/Engine/Objects/Actor.h
  src/Engine/Objects/SpriteObject.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/GUI/GUIFont.h
Labels: 👍Approved

#729 Renamings following the codestyle
  src/Application/Game.cpp
  src/Application/GameOver.cpp
  src/Engine/Conditions.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Graphics/Vis.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/PriceCalculator.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Spells/Spells.h
  src/Engine/Tables/TileTable.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIQuickReference.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UIShops.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/Mouse.cpp
  src/Utility/Geometry/Plane.h
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#731 Getting rid of facePlane_old
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/SpriteObject.cpp
Labels: 👍Approved

#732 More renamings in LegacyImages
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
Labels: 👍Approved

#734 fixes
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/GUI/GUIEnums.h
  src/Io/KeyboardInputHandler.cpp
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioPlayer.h
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#736 Dropped facePlane_old
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/PortalFunctions.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Utility/Geometry/Plane.h
Labels: 👍Approved

#749 Fix monster killed event
  src/Engine/Events.cpp
  src/Engine/Events/EventEnums.h
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/NPC.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Tests/TestIssues.cpp
Labels: 👍Approved

#748 Support timer triggers
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/Processor.cpp
  src/Engine/Events/Processor.h
Labels: 👍Approved

#751 Fix event timers
  src/Engine/Events.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/Processor.cpp
  src/Engine/Events/Processor.h
  src/Engine/Time.h
Labels: 👍Approved
