Repository OpenEnroth/OpenEnroth, pull requests merged in 2023-01, with the labels that each got.

#357 Mm6 and Mm8 path resolution + change path env vars
  README.md
  src/Application/CMakeLists.txt
  src/Application/Game.cpp
  src/Application/GamePathResolver.cpp
  src/Application/GamePathResolver.h
  src/Engine/Graphics/Direct3D/Render.cpp
  src/Platform/Platform.h
  src/Platform/Sdl/SdlPlatform.cpp
  src/Platform/Sdl/SdlPlatform.h
  src/Platform/Win/WinPlatform.cpp
  src/Platform/Win/WinPlatform.h
  src/Utility/DataPath.cpp
  src/Utility/DataPath.h
  test/Testing/Engine/TestPlatform.cpp
  test/Testing/Engine/TestPlatform.h
Labels: ❓Questions

#363 Minor fixes in HACKING
  HACKING.md
Labels: 👍👍Very Approved

#361 Minor cleanup
  src/Engine/Graphics/DecorationList.h
  src/Engine/Graphics/Direct3D/Render.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Overlays.h
  src/Engine/Graphics/Sprites.h
  src/Engine/LOD.h
  src/Engine/Objects/Chest.h
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/ObjectList.h
  src/Engine/Objects/Player.cpp
  src/Engine/Party.h
  src/Engine/Serialization/Deserializer.h
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Tables/IconFrameTable.h
  src/Engine/Tables/PlayerFrameTable.h
  src/Engine/Tables/TileFrameTable.h
  src/Engine/ZlibWrapper.h
  src/GUI/GUIProgressBar.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIDialogue.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UITransition.cpp
  src/Media/Audio/AudioPlayer.h
  src/Media/Media.h
  src/Utility/CMakeLists.txt
  src/Utility/DataPath.h
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
  src/Utility/Memory/MemSet.h
Labels: 👍👍Very Approved

#362 Proxy platform classes
  src/Platform/CMakeLists.txt
  src/Platform/Proxy/ProxyBase.h
  src/Platform/Proxy/ProxyEventLoop.cpp
  src/Platform/Proxy/ProxyEventLoop.h
  src/Platform/Proxy/ProxyGamepad.cpp
  src/Platform/Proxy/ProxyGamepad.h
  src/Platform/Proxy/ProxyOpenGLContext.cpp
  src/Platform/Proxy/ProxyOpenGLContext.h
  src/Platform/Proxy/ProxyPlatform.cpp
  src/Platform/Proxy/ProxyPlatform.h
  src/Platform/Proxy/ProxyWindow.cpp
  src/Platform/Proxy/ProxyWindow.h
  test/Testing/Engine/CMakeLists.txt
  test/Testing/Engine/TestEventLoop.cpp
  test/Testing/Engine/TestEventLoop.h
  test/Testing/Engine/TestGamepad.cpp
  test/Testing/Engine/TestGamepad.h
  test/Testing/Engine/TestOpenGLContext.cpp
  test/Testing/Engine/TestOpenGLContext.h
  test/Testing/Engine/TestPlatform.cpp
  test/Testing/Engine/TestPlatform.h
  test/Testing/Engine/TestState.h
  test/Testing/Engine/TestWindow.cpp
  test/Testing/Engine/TestWindow.h
Labels: 👍👍Very Approved

#359 Bugs + bloodsplats
  src/Engine/Engine.cpp
  src/Engine/Graphics/BSPModel.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/Direct3D/Render.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/ParticleEngine.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Monsters.cpp
  src/Engine/Objects/Monsters.h
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Serialization/LegacyImages.cpp
  src/Engine/Serialization/LegacyImages.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/SpellFxRenderer.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/Utility/Color.h
Labels: 👍Approved

#370 Mainly TODOs & doc fixes
  src/Platform/Platform.h
  src/Platform/PlatformEventHandler.h
  src/Platform/PlatformEventLoop.h
  src/Platform/PlatformEvents.h
  src/Platform/PlatformGamepad.h
  src/Platform/PlatformLogger.h
  src/Platform/PlatformOpenGLContext.h
  src/Platform/PlatformWindow.h
  src/Utility/Flags.h
  src/Utility/FreeDeleter.h
  src/Utility/IndexedArray.h
  src/Utility/Random/Random.cpp
  src/Utility/Random/Random.h
  test/Bin/GameTest/GameTestOptions.cpp
Labels: 👍👍Very Approved

#371 Dropping unused file, forgot to drop it in the previous PR
  src/Platform/CMakeLists.txt
  src/Platform/PlatformKey.cpp
  src/Platform/PlatformKey.h
Labels: 👍👍Very Approved

#360 Rename project to OpenEnroth
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  CMakeModules/Git.cmake
  Doxyfile
  HACKING.md
  README.md
  src/Application/GameConfig.h
  src/Engine/Engine.cpp
  src/Launcher/Launcher.Windows/Resource.rc
  src/Launcher/Launcher.Windows/src/Application.cpp
  src/Launcher/Launcher.Windows/src/Launcher.cpp
  src/Library/Json/CMakeLists.txt
  src/Library/Serialization/CMakeLists.txt
  src/Utility/CMakeLists.txt
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTestMain.cpp
  test/Bin/UnitTest/CMakeLists.txt
  test/Tests/CMakeLists.txt
Labels: 👍Approved

#374 Mostly resolving TODOs
  src/Application/GameConfig.cpp
  src/Application/GameConfig.h
  src/Application/GameMenu.cpp
  src/Application/GameOptions.cpp
  src/Application/GameWindowHandler.cpp
  src/Application/GameWindowHandler.h
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/IRenderFactory.cpp
  src/Engine/Graphics/IRenderFactory.h
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/Graphics/Nuklear.cpp
  src/Engine/Graphics/Nuklear.h
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/RendererType.h
  src/GUI/GUIButton.h
  src/GUI/GUIWindow.h
  src/GUI/UI/UIGame.cpp
  src/Io/IKeyboardController.h
  src/Io/InputAction.cpp
  src/Io/InputAction.h
  src/Io/Key.h
  src/Io/KeyboardActionMapping.h
  src/Io/KeyboardInputHandler.h
  src/Io/Mouse.h
  src/Platform/CMakeLists.txt
  src/Platform/Platform.h
  src/Platform/PlatformEnums.h
  src/Platform/PlatformEventLoop.h
  src/Platform/PlatformEvents.h
  src/Platform/PlatformKey.h
  src/Platform/PlatformLogger.h
  src/Platform/PlatformModifiers.h
  src/Platform/PlatformMouseButton.h
  src/Platform/PlatformOpenGLOptions.h
  src/Platform/PlatformWindow.h
  src/Platform/Sdl/SdlEnumTranslation.cpp
  src/Platform/Sdl/SdlEnumTranslation.h
  src/Platform/Sdl/SdlEventLoop.cpp
  src/Platform/Sdl/SdlEventLoop.h
  src/Platform/Sdl/SdlWindow.cpp
  test/Testing/Game/GameWrapper.h
Labels: 👍Approved

#376 Continuing with TODOs
  src/Application/Game.cpp
  src/Application/Game.h
  src/Application/GameTraceHandler.cpp
  src/Application/GameTraceHandler.h
  src/Application/GameWindowHandler.cpp
  src/Application/GameWindowHandler.h
  src/Engine/Graphics/NuklearEventHandler.cpp
  src/Engine/Graphics/NuklearEventHandler.h
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/SaveLoad.cpp
  src/GUI/UI/UIHouses.cpp
  src/Library/Trace/CMakeLists.txt
  src/Library/Trace/EventTrace.cpp
  src/Library/Trace/EventTrace.h
  src/Library/Trace/EventTracer.cpp
  src/Library/Trace/EventTracer.h
  src/Library/Trace/PaintEvent.h
  src/Platform/Filters/FilteringEventHandler.cpp
  src/Platform/Filters/FilteringEventHandler.h
  src/Platform/Filters/PlatformEventFilter.cpp
  src/Platform/Filters/PlatformEventFilter.h
  src/Platform/PlatformEnums.h
  src/Platform/PlatformEventHandler.cpp
  src/Platform/PlatformEventHandler.h
  src/Platform/PlatformEvents.h
  src/Platform/Sdl/SdlEventLoop.cpp
  src/Platform/Sdl/SdlEventLoop.h
  src/Utility/Random/Random.h
  test/Testing/Engine/CMakeLists.txt
  test/Testing/Engine/TestProxy.cpp
  test/Testing/Engine/TestProxy.h
  test/Testing/Game/GameTest.cpp
  test/Testing/Game/GameWrapper.cpp
Labels: 👍Approved

#380 Split random number generators in two
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Engine/Engine.cpp
  src/Engine/Events.cpp
  src/Engine/Graphics/Direct3D/Render.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Level/Decoration.cpp
  src/Engine/Graphics/OpenGL/RenderOpenGL.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/ParticleEngine.cpp
  src/Engine/Graphics/RenderBase.cpp
  src/Engine/Graphics/Weather.cpp
  src/Engine/MapInfo.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/ItemTable.cpp
  src/Engine/Objects/Items.cpp
  src/Engine/Objects/NPC.cpp
  src/Engine/Objects/Player.cpp
  src/Engine/Objects/Player.h
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/Tables/PlayerFrameTable.cpp
  src/Engine/Tables/TileTable.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Spellbook.cpp
  src/GUI/UI/UIArena.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIGuilds.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UIShops.cpp
  src/Library/CMakeLists.txt
  src/Library/Random/CMakeLists.txt
  src/Library/Random/MersenneTwisterRandomEngine.h
  src/Library/Random/NonRandomEngine.h
  src/Library/Random/Random.cpp
  src/Library/Random/Random.h
  src/Library/Random/RandomEngine.cpp
  src/Library/Random/RandomEngine.h
  src/Library/Trace/CMakeLists.txt
  src/Library/Trace/EventTracer.cpp
  src/Utility/CMakeLists.txt
  src/Utility/Random/Random.cpp
  src/Utility/Random/Random.h
  src/Utility/Random/RandomEngine.h
  test/Bin/GameTest/GameTestMain.cpp
  test/Testing/Game/GameWrapper.cpp
Labels: 👍Approved

#384 drop launcher
  Doxyfile
  README.md
  src/CMakeLists.txt
  src/Launcher/CMakeLists.txt
  src/Launcher/Launcher.Windows/CMakeLists.txt
  src/Launcher/Launcher.Windows/Resource.aps
  src/Launcher/Launcher.Windows/Resource.rc
  src/Launcher/Launcher.Windows/ico128.ico
  src/Launcher/Launcher.Windows/resource.h
  src/Launcher/Launcher.Windows/shield-flip.bmp
  src/Launcher/Launcher.Windows/shield.bmp
  src/Launcher/Launcher.Windows/src/Application.cpp
  src/Launcher/Launcher.Windows/src/Application.h
  src/Launcher/Launcher.Windows/src/ApplicationConfig.h
  src/Launcher/Launcher.Windows/src/Launcher.cpp
Labels: 👍Approved

#385 Minor fixes to make things more deterministic
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Party.cpp
  src/Engine/Time.h
Labels: 👍Approved
