Repository OpenEnroth/OpenEnroth, pull requests merged in 2024-03, with the labels that each got.

#1531 Fixes #1471
  src/Application/Game.cpp
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 🥺Ready for Review

#1533 Fixes #1509
  src/Engine/Engine.cpp
  src/Engine/Engine.h
  src/Engine/Graphics/BspRenderer.cpp
  src/GUI/UI/Books/MapBook.cpp
  src/GUI/UI/UIGame.cpp
Labels: 🥺Ready for Review

#1534 Renaming speed -> velocity
  src/Application/Game.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TeleportPoint.cpp
  src/GUI/UI/NPCTopics.cpp
Labels: 🥺Ready for Review

#1537 Working on TODOs
  src/Application/Game.cpp
  src/Application/GameStarter.cpp
  src/Engine/ArenaEnumFunctions.h
  src/Engine/ArenaEnums.h
  src/Engine/CMakeLists.txt
  src/Engine/Components/Deterministic/EngineDeterministicComponent.h
  src/Engine/Engine.cpp
  src/Engine/Graphics/Renderer/BaseRenderer.cpp
  src/Engine/Graphics/Renderer/BaseRenderer.h
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Graphics/TurnBasedOverlay.cpp
  src/Engine/Graphics/TurnBasedOverlay.h
  src/Engine/Objects/Character.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/GUI/GUIDialogues.h
  src/GUI/GUIFont.cpp
  src/GUI/GUIFont.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/NPCTopics.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIDialogue.cpp
  src/GUI/UI/UIHouses.cpp
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 👍Approved

#1539 Tapes for arbitrary data pushed from the engine
  src/Application/GameKeyboardController.cpp
  src/Bin/OpenEnroth/OpenEnrothOptions.cpp
  src/Engine/CMakeLists.txt
  src/Engine/Components/Trace/EngineTracePlayer.cpp
  src/Engine/Components/Trace/EngineTracePlayer.h
  src/Engine/Components/Trace/EngineTraceSimplePlayer.cpp
  src/Engine/Components/Trace/EngineTraceSimplePlayer.h
  src/Engine/Engine.h
  src/Engine/EngineCallObserver.h
  src/Engine/Graphics/Image.cpp
  src/Engine/Graphics/Image.h
  src/Engine/Graphics/ImageLoader.h
  src/Engine/Graphics/Renderer/NullRenderer.cpp
  src/Engine/Graphics/Renderer/NullRenderer.h
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Graphics/Renderer/OpenGLRenderer.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/Media/Audio/AudioPlayer.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0000.cpp
  test/Bin/GameTest/GameTests_0500.cpp
  test/Bin/GameTest/GameTests_1000.cpp
  test/Testing/Game/CMakeLists.txt
  test/Testing/Game/CommonTapeRecorder.cpp
  test/Testing/Game/CommonTapeRecorder.h
  test/Testing/Game/GameTest.cpp
  test/Testing/Game/TestCallObserver.h
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
  test/Testing/Game/TestTape.h
Labels: 🥺Ready for Review

#1542 Clear spells between test runs
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  test/Testing/Game/TestController.cpp
Labels: 🥺Ready for Review

#1543 Test for #1535
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/CastSpellInfo.h
  src/GUI/GUIMessageQueue.cpp
  src/GUI/GUIMessageQueue.h
  test/Bin/GameTest/GameTests_1500.cpp
  test/Testing/Game/TestController.cpp
Labels: 🥺Ready for Review

#1544 Add test for #1532
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 🥺Ready for Review

#1549 Add -DCMAKE_BUILD_TYPE=Debug to HACKING instructions.
  HACKING.md
Labels: 🥺Ready for Review

#1546 Minor cleanup
  src/Application/GameKeyboardController.cpp
  src/Application/GameKeyboardController.h
  src/Io/KeyboardActionMapping.cpp
  src/Io/KeyboardInputHandler.cpp
  src/Io/KeyboardInputHandler.h
Labels: 🥺Ready for Review

#1545 Tests
  src/Media/Audio/AudioPlayer.cpp
  src/Media/Audio/AudioSamplePool.cpp
  src/Media/Audio/AudioSamplePool.h
  src/Media/Audio/SoundEnums.h
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 🥺Ready for Review

#1550 Pressing & releasing a key inside a single frame now works
  src/Application/GameKeyboardController.cpp
  src/Io/KeyboardInputHandler.cpp
  test/Bin/GameTest/CMakeLists.txt
Labels: 🥺Ready for Review

#1551 Properly report problems with prebuilt deps
  CMakeModules/Dependencies.cmake
Labels: 🥺Ready for Review

#1552 Fixes #880
  src/Engine/Objects/SpriteObject.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0500.cpp
Labels: 🥺Ready for Review

#1555 Floats split
  src/Application/Game.cpp
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/Processor.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Level/Decoration.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Renderer/BaseRenderer.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Party.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Spells/Spells.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0500.cpp
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 🥺Ready for Review

#1559 Floats split 2
  src/Engine/AttackList.cpp
  src/Engine/AttackList.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  test/Bin/GameTest/CMakeLists.txt
Labels: 🥺Ready for Review

#1554 Dropped the usage of new.lod
  src/Application/Game.cpp
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/Engine.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/SaveLoad.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/Utility/Memory/Blob.cpp
  src/Utility/Memory/Blob.h
Labels: 🥺Ready for Review

#1568 Fix 326
  HACKING.md
  src/Application/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/Level/CMakeLists.txt
  src/Engine/Graphics/Renderer/CMakeLists.txt
Labels: 🥺Ready for Review

#1564 Enable OSX M1
  .github/workflows/macos.yml
  CMakeLists.txt
  CMakeModules/Dependencies.cmake
  CMakeModules/Detection.cmake
  src/Bin/CodeGen/CMakeLists.txt
  src/Bin/LodTool/CMakeLists.txt
  src/Bin/OpenEnroth/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/Engine/Engine.cpp
  src/Library/Environment/Android/CMakeLists.txt
  src/Library/Environment/Posix/CMakeLists.txt
  src/Library/Environment/Win/CMakeLists.txt
  src/Library/StackTrace/CMakeLists.txt
  src/Utility/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: 👍Approved

#1565 BugFix #1556: Missing NPC name on simple NPC houses
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
Labels: ❓Questions

#1570 Docs, TODOs & minor cleanup
  .github/workflows/macos.yml
  CMakeLists.txt
  CMakeModules/Dependencies.cmake
  CMakeModules/Detection.cmake
  README.md
  src/Application/GameStarter.cpp
  src/Engine/Components/Control/EngineController.cpp
  src/Engine/EngineCallObserver.h
  src/Engine/LOD.cpp
  src/Engine/LOD.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/Utility/Streams/TempFileOutputStream.h
  test/Testing/Game/CommonTapeRecorder.h
Labels: 🥺Ready for Review
