Repository OpenEnroth/OpenEnroth, pull requests merged in 2024-04, with the labels that each got.

#1575 why is the liscense the lgplv3 not gplv3?
  LICENSE
Labels: 👍Approved

#1580 Add bounds checks to GetFrameTexture
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Graphics/TextureFrameTable.cpp
Labels: 🥺Ready for Review

#1582 Add test for #1253
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 🥺Ready for Review

#1581 Consistent use of int64_t in TextureFrameTable
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Graphics/TextureFrameTable.h
Labels: 🥺Ready for Review

#1583 Add test for #1175 and #1275
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 🥺Ready for Review

#1585 Logger fixes
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Engine/Graphics/NuklearLogSink.cpp
  src/Library/Logger/CMakeLists.txt
  src/Library/Logger/DistLogSink.cpp
  src/Library/Logger/DistLogSink.h
  src/Library/Logger/LogCategory.h
  src/Library/Logger/LogSink.cpp
  src/Library/Logger/LogSink.h
  src/Library/Logger/LogSinkComposite.cpp
  src/Library/Logger/Logger.cpp
  src/Library/Logger/Logger.h
Labels: 🥺Ready for Review

#1587 Documentation for lua scripts and HACKING.md update - Part #1
  HACKING.md
  resources/ui/commands.lua
  resources/ui/console.lua
  resources/ui/init.lua
  resources/ui/logger.lua
  resources/ui/ui_debug_hud.lua
  resources/ui/utils.lua
Labels: 👍Approved

#1588 Dont update FACE_TEXTURE_FRAME from delta attribs
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Snapshots/CompositeSnapshots.cpp
Labels: 🥺Ready for Review

#1590 More cleanup
  HACKING.md
  src/Application/GameStarter.cpp
  src/Bin/CodeGen/CodeGenMap.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Library/Environment/Android/AndroidEnvironment.cpp
  src/Library/Environment/Android/AndroidEnvironment.h
  src/Library/Environment/Interface/Environment.h
  src/Library/Environment/Posix/PosixEnvironment.cpp
  src/Library/Environment/Posix/PosixEnvironment.h
  src/Library/Environment/Win/WinEnvironment.cpp
  src/Library/Environment/Win/WinEnvironment.h
  src/Utility/CMakeLists.txt
  src/Utility/Tests/TransparentFunctors_ut.cpp
  src/Utility/TransparentFunctors.h
Labels: 🥺Ready for Review

#1594 Floats reverts
  .github/workflows/macos.yml
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0500.cpp
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 🥺Ready for Review

#1595 Make test 1331 do what's written in the comment.
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 🥺Ready for Review

#1599 Fix & test #1547 & some minor cleanup
  src/Application/Game.cpp
  src/Application/GameOver.cpp
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/Engine/Objects/ActorEnums.h
  src/Engine/Objects/Character.cpp
  src/Engine/TeleportPoint.h
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UITransition.cpp
  src/Utility/String.h
  test/Bin/GameTest/GameTests_1500.cpp
  test/Testing/Game/ActorTapeRecorder.cpp
  test/Testing/Game/ActorTapeRecorder.h
Labels: 🥺Ready for Review

#1601 Cleanup
  src/Application/GameConfig.h
  src/Application/GameKeyboardController.h
  src/Application/GameOver.cpp
  src/Engine/Engine.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/SaveLoad.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Time/Duration.h
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/Io/KeyboardInputHandler.cpp
  test/Bin/GameTest/GameTests_1000.cpp
  test/Bin/GameTest/GameTests_1500.cpp
  test/Testing/Game/CharacterTapeRecorder.cpp
  test/Testing/Game/CharacterTapeRecorder.h
Labels: 🥺Ready for Review

#1604 Scripts: Moved the lua files to the "scripts" folder
  HACKING.md
  resources/scripts/commands.lua
  resources/scripts/console.lua
  resources/scripts/dev/ui_debug_hud.lua
  resources/scripts/init.lua
  resources/scripts/logger.lua
  resources/scripts/utils.lua
  src/Engine/Graphics/Nuklear.cpp
Labels: 🥺Ready for Review

#1603 More cleanup
  CMakeLists.txt
  HACKING.md
  src/Engine/Engine.cpp
  src/Engine/Objects/MonsterEnumFunctions.h
  src/Engine/Objects/MonsterEnums.h
  src/Library/Platform/Application/PlatformApplication.cpp
  src/Library/Platform/Application/PlatformApplication.h
  src/Library/Platform/Application/PlatformComponentStorage.cpp
  src/Library/Platform/Application/PlatformComponentStorage.h
  src/Library/Serialization/EnumSerialization.h
  src/Library/Serialization/Tests/Serialization_ut.cpp
  src/Utility/FileSystem.cpp
  src/Utility/String.cpp
  src/Utility/String.h
  src/Utility/Tests/UnicodeCrt_ut.cpp
  test/Testing/Game/TestController.cpp
  test/Testing/Game/TestController.h
Labels: 🥺Ready for Review

#1600 Floats split
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Objects/SpriteObject.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UIPopup.cpp
  src/Library/Environment/Win/WinEnvironment.cpp
  src/Utility/Win/Unicode.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0500.cpp
Labels: 🥺Ready for Review

#1607 More floats
  src/Engine/Events/Processor.cpp
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Party.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/TurnEngine/TurnEngine.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0000.cpp
  test/Bin/GameTest/GameTests_1000.cpp
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 🥺Ready for Review

#1608 Scripts: Lua utility and final set of commands
  resources/scripts/console.lua
  resources/scripts/dev/commands/alignment_command.lua
  resources/scripts/dev/commands/class_command.lua
  resources/scripts/dev/commands/cls_command.lua
  resources/scripts/dev/commands/command_manager.lua
  resources/scripts/dev/commands/command_utils.lua
  resources/scripts/dev/commands/condition_command.lua
  resources/scripts/dev/commands/food_command.lua
  resources/scripts/dev/commands/game_commands.lua
  resources/scripts/dev/commands/gold_command.lua
  resources/scripts/dev/commands/hp_command.lua
  resources/scripts/dev/commands/inventory_command.lua
  resources/scripts/dev/commands/mana_command.lua
  resources/scripts/dev/commands/skillpoints_command.lua
  resources/scripts/dev/commands/skills_command.lua
  resources/scripts/dev/commands/xp_command.lua
  resources/scripts/mmbindings.lua
  resources/scripts/utils.lua
  src/Application/CMakeLists.txt
  src/Application/GameLuaBindings.cpp
  src/Application/GameLuaBindings.h
  src/Application/LuaItemQueryTable.h
  src/Engine/Objects/CharacterEnumFunctions.h
Labels: ❓Questions

#1611 Floats
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Objects/Actor.h
  src/Engine/Objects/SpriteObject.cpp
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_0000.cpp
Labels: 🥺Ready for Review

#1614 Cleanup
  HACKING.md
  src/Application/GameStarter.cpp
  src/Application/GameStarter.h
  src/Engine/Components/Control/EngineController.h
  src/Engine/SaveLoad.cpp
  src/Library/Lod/LodWriter.cpp
  src/Library/Lod/Tests/LodWriter_ut.cpp
  src/Library/Logger/DistLogSink.cpp
  src/Library/Logger/DistLogSink.h
  src/Library/Logger/Logger.cpp
  src/Library/Logger/Logger.h
  src/Library/Platform/Application/PlatformApplication.cpp
  src/Library/Platform/Application/PlatformApplication.h
  src/Library/Platform/Application/PlatformComponentStorage.h
  src/Scripting/InputScriptEventHandler.cpp
  src/Scripting/InputScriptEventHandler.h
  src/Scripting/ScriptLogSink.cpp
  src/Scripting/ScriptLogSink.h
  src/Scripting/ScriptingSystem.cpp
  src/Scripting/ScriptingSystem.h
  src/Utility/CMakeLists.txt
  src/Utility/Streams/TempFileOutputStream.cpp
  src/Utility/Streams/TempFileOutputStream.h
  test/Testing/Game/TestController.cpp
Labels: 🥺Ready for Review
