Repository OpenEnroth/OpenEnroth, pull requests merged in 2024-10, with the labels that each got.

#1799 Fix #1793
  src/Application/Game.cpp
  src/Application/GameMenu.cpp
  src/Application/GameOver.cpp
  src/Application/GameOver.h
  src/Application/GameWindowHandler.cpp
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/GUIWindow.cpp
  src/GUI/GUIWindow.h
  src/GUI/UI/UIGameOver.cpp
  src/GUI/UI/UIGameOver.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIMainMenu.cpp
  src/GUI/UI/UIPartyCreation.cpp
  src/Io/Mouse.cpp
  src/Media/MediaPlayer.cpp
  test/Bin/CMakeLists.txt
Labels: 🥺Ready for Review

#1805 Unified am/pm handling
  src/Engine/Localization.h
  src/Engine/Party.h
  src/Engine/Time/Time.h
  src/GUI/UI/Books/CalendarBook.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIRest.cpp
  src/GUI/UI/UISaveLoad.cpp
Labels: 🥺Ready for Review

#1806 Started moving out data classes
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/CodeGen/CodeGenEnums.cpp
  src/Bin/CodeGen/CodeGenEnums.h
  src/Engine/ArenaEnumFunctions.h
  src/Engine/CMakeLists.txt
  src/Engine/Data/AutonoteData.h
  src/Engine/Data/AutonoteEnums.h
  src/Engine/Data/AwardData.h
  src/Engine/Data/AwardEnums.h
  src/Engine/Data/CMakeLists.txt
  src/Engine/Data/HouseData.h
  src/Engine/Data/HouseEnums.h
  src/Engine/Engine.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventMap.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/Items.cpp
  src/Engine/PriceCalculator.cpp
  src/Engine/PriceCalculator.h
  src/Engine/Tables/AutonoteTable.cpp
  src/Engine/Tables/AutonoteTable.h
  src/Engine/Tables/AwardTable.cpp
  src/Engine/Tables/AwardTable.h
  src/Engine/Tables/BuildingTable.h
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/HouseTable.cpp
  src/Engine/Tables/HouseTable.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/AutonotesBook.cpp
  src/GUI/UI/Books/AutonotesBook.h
  src/GUI/UI/Houses/MagicGuild.cpp
  src/GUI/UI/Houses/MercenaryGuild.cpp
  src/GUI/UI/Houses/Shops.cpp
  src/GUI/UI/Houses/Shops.h
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Temple.cpp
  src/GUI/UI/Houses/TownHall.cpp
  src/GUI/UI/Houses/Training.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/NPCTopics.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  src/GUI/UI/UIPopup.cpp
  src/GUI/UI/UITransition.cpp
Labels: 👍Approved

#1810 CharacterExpressionID is now CharacterPortrait
  src/Application/Game.cpp
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/CodeGen/CodeGenEnums.cpp
  src/Bin/CodeGen/CodeGenEnums.h
  src/Bin/CodeGen/CodeGenOptions.cpp
  src/Bin/CodeGen/CodeGenOptions.h
  src/Engine/Engine.cpp
  src/Engine/Events/EventIR.cpp
  src/Engine/Events/EventIR.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/CharacterEnumFunctions.cpp
  src/Engine/Objects/CharacterEnumFunctions.h
  src/Engine/Objects/CharacterEnums.h
  src/Engine/Party.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Tables/CharacterFrameTable.cpp
  src/Engine/Tables/CharacterFrameTable.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/GameTests_0000.cpp
  test/Bin/GameTest/GameTests_0500.cpp
  test/Bin/GameTest/GameTests_1000.cpp
  test/Bin/GameTest/GameTests_1500.cpp
  test/Testing/Game/CharacterTapeRecorder.cpp
  test/Testing/Game/CharacterTapeRecorder.h
Labels: 👍Approved

#1812 Fixed #1807
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Houses/Tavern.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#1811 Moved HouseId to HouseEnums.h
  src/Application/Game.cpp
  src/Arcomage/Arcomage.cpp
  src/Bin/CodeGen/CodeGen.cpp
  src/Bin/CodeGen/CodeGenEnums.h
  src/Engine/Data/CMakeLists.txt
  src/Engine/Data/HouseEnumFunctions.h
  src/Engine/Data/HouseEnums.h
  src/Engine/Events/EventIR.h
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Items.h
  src/Engine/Objects/MonsterEnumFunctions.h
  src/Engine/Party.h
  src/Engine/Tables/HouseTable.cpp
  src/Engine/Tables/HouseTable.h
  src/Engine/Tables/NPCTable.h
  src/GUI/GUIWindow.h
  src/GUI/UI/Houses/Tavern.cpp
  src/GUI/UI/Houses/Transport.cpp
  src/GUI/UI/NPCTopics.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIHouses.cpp
  src/GUI/UI/UIHouses.h
  test/Testing/Game/CommonTapeRecorder.h
Labels: 👍Approved

#1815 More cleanup in Table* code
  src/Application/Game.cpp
  src/Engine/Data/CMakeLists.txt
  src/Engine/Data/FrameEnums.h
  src/Engine/Data/HistoryData.h
  src/Engine/Data/IconFrameData.h
  src/Engine/Data/PortraitFrameData.h
  src/Engine/Engine.cpp
  src/Engine/Events/CMakeLists.txt
  src/Engine/Events/EventEnumFunctions.h
  src/Engine/Events/EventIR.cpp
  src/Engine/Graphics/TextureFrameTable.cpp
  src/Engine/Graphics/TextureFrameTable.h
  src/Engine/Graphics/TurnBasedOverlay.cpp
  src/Engine/Graphics/TurnBasedOverlay.h
  src/Engine/Objects/CMakeLists.txt
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Character.h
  src/Engine/Objects/CharacterEnums.h
  src/Engine/Objects/TalkAnimation.cpp
  src/Engine/Objects/TalkAnimation.h
  src/Engine/Party.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Snapshots/TableSerialization.cpp
  src/Engine/Snapshots/TableSerialization.h
  src/Engine/SpellFxRenderer.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/CharacterFrameTable.cpp
  src/Engine/Tables/CharacterFrameTable.h
  src/Engine/Tables/FrameTableInc.h
  src/Engine/Tables/HistoryTable.cpp
  src/Engine/Tables/HistoryTable.h
  src/Engine/Tables/HouseTable.h
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/IconFrameTable.h
  src/Engine/Tables/PortraitFrameTable.cpp
  src/Engine/Tables/PortraitFrameTable.h
  src/Engine/Tables/StorylineTextTable.cpp
  src/Engine/Tables/StorylineTextTable.h
  src/Engine/mm7_data.cpp
  src/GUI/GUIProgressBar.cpp
  src/GUI/GUIWindow.cpp
  src/GUI/UI/Books/JournalBook.cpp
  src/GUI/UI/UIGame.cpp
  src/GUI/UI/UIGame.h
  src/GUI/UI/UIHouseEnums.h
  src/GUI/UI/UIPartyCreation.cpp
  src/GUI/UI/UIPopup.cpp
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 👍Approved

#1821 Show torchlight & wizard eye on quick reference screen
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#1820 Enable assertions in release builds
  CMakeLists.txt
  CMakeModules/Assertions.cmake
Labels: 👍Approved

#1800 Logging to a file
  CMakeLists.txt
  src/Application/Startup/CMakeLists.txt
  src/Application/Startup/FileSystemStarter.cpp
  src/Application/Startup/FileSystemStarter.h
  src/Application/Startup/GameStarter.cpp
  src/Application/Startup/GameStarter.h
  src/Application/Startup/LogStarter.cpp
  src/Application/Startup/LogStarter.h
  src/Engine/EngineFileSystem.cpp
  src/Engine/EngineFileSystem.h
  src/Library/FileSystem/Memory/MemoryFileSystemOutputStream.cpp
  src/Library/FileSystem/Memory/Tests/MemoryFileSystem_ut.cpp
  src/Library/Platform/Interface/Platform.h
  src/Library/Platform/Sdl/SdlPlatform.cpp
  src/Library/Platform/Sdl/SdlPlatform.h
  src/Library/Platform/Sdl/SdlPlatformSharedState.cpp
  src/Library/Platform/Sdl/SdlPlatformSharedState.h
  src/Utility/Streams/BlobOutputStream.h
  src/Utility/String/Format.h
Labels: 👍Approved

#1827 Fix texture offset on indoor doors
  src/Engine/Graphics/Indoor.cpp
Labels: 👍Approved

#1825 Add test for unicode functions & fix MSVC log sink throwing an exception
  src/Library/Logger/LogSink.cpp
  src/Utility/CMakeLists.txt
  src/Utility/Win/Tests/Unicode_ut.cpp
  src/Utility/Win/Unicode.cpp
Labels: 👍Approved

#1830 Some cleanup in face flags
  src/Engine/Graphics/FaceEnums.h
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Graphics/Vis.cpp
Labels: 👍Approved

#1833 Node 20 changes
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: 👍Approved

#1826 Run flatpak tests w/o creating a custom target for them
  distribution/linux/flatpak/dev.io.github.openenroth.openenroth.yml
  distribution/linux/flatpak/io.github.openenroth.openenroth.yml
  test/Bin/CMakeLists.txt
Labels: 🥺Ready for Review

#1834 Cleanup in TileTable
  src/Engine/Data/CMakeLists.txt
  src/Engine/Data/TileData.h
  src/Engine/Data/TileEnums.h
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Snapshots/TableSerialization.cpp
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/TileTable.cpp
  src/Engine/Tables/TileTable.h
Labels: 👍Approved

#1835 Png screenshots
  .github/workflows/macos.yml
  CMakeModules/Dependencies.cmake
  src/Application/GameOver.cpp
  src/Application/GameWindowHandler.cpp
  src/Engine/Graphics/ImageLoader.cpp
  src/Engine/SaveLoad.cpp
  src/Library/Image/CMakeLists.txt
  src/Library/Image/Pcx.cpp
  src/Library/Image/Pcx.h
  src/Library/Image/Png.cpp
  src/Library/Image/Png.h
Labels: 👍Approved, 🥺Ready for Review

#1838 LodTool extract added
  src/Bin/LodTool/CMakeLists.txt
  src/Bin/LodTool/LodTool.cpp
  src/Bin/LodTool/LodToolOptions.cpp
  src/Bin/LodTool/LodToolOptions.h
  src/Library/Image/Pcx.cpp
  src/Library/Image/Png.cpp
  src/Library/Image/Png.h
  src/Library/LodFormats/LodFormats.cpp
Labels: 👍Approved

#1839 Nicer lava & portals animation
  resources/shaders/glbspshader.frag
Labels: 👍Approved

#1841 Cleanup
  src/Engine/Engine.h
  src/Engine/Events/EventInterpreter.cpp
  src/Engine/Events/EventInterpreter.h
  src/Engine/Graphics/CMakeLists.txt
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/OutdoorTerrain.cpp
  src/Engine/Graphics/OutdoorTerrain.h
  src/Engine/Graphics/Polygon.h
  src/Engine/Graphics/Renderer/NullRenderer.cpp
  src/Engine/Graphics/Renderer/NullRenderer.h
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Graphics/Renderer/OpenGLRenderer.h
  src/Engine/Graphics/Renderer/Renderer.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
  src/Engine/mm7_data.cpp
  src/Engine/mm7_data.h
  src/Io/Key.cpp
Labels: 👍Approved

#1847 Add TODOs & fix includes for HRTF fix
  src/Application/GameConfig.h
  src/Media/Audio/OpenALSoundProvider.cpp
  src/Media/Audio/OpenALSoundProvider.h
Labels: 👍Approved

#1843 More terrain related cleanup
  src/Engine/Data/TileEnums.h
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Collisions.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/OutdoorTerrain.cpp
  src/Engine/Graphics/OutdoorTerrain.h
  src/Engine/Graphics/RenderEntities.h
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Objects/SpriteObject.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/Library/Geometry/Vec.h
Labels: 👍Approved

#1836 Work on stairs
  src/Engine/Graphics/Collisions.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#1850 Fix minimap construction
  src/Engine/Graphics/BspRenderer.cpp
  src/Engine/Graphics/BspRenderer.h
  src/Engine/Graphics/Camera.cpp
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
Labels: 🥺Ready for Review

#1855 Resolving terrain-related rounding TODOs
  src/Engine/Graphics/Outdoor.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_0500.cpp
Labels: 👍Approved

#1856 Renamings in tile enums
  src/Engine/Data/TileData.h
  src/Engine/Data/TileEnums.h
  src/Engine/Graphics/DecalBuilder.cpp
  src/Engine/Graphics/DecalBuilder.h
  src/Engine/Graphics/Outdoor.cpp
  src/Engine/Graphics/Outdoor.h
  src/Engine/Graphics/OutdoorTerrain.cpp
  src/Engine/Graphics/OutdoorTerrain.h
  src/Engine/Graphics/Renderer/OpenGLRenderer.cpp
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Tables/TileTable.cpp
  src/Engine/Tables/TileTable.h
Labels: 👍Approved

#1859 Fix debug menu not working on gcc
  src/Scripting/ScriptingSystem.cpp
Labels: 👍Approved

#1857 Fix #1824
  src/GUI/Overlay/OverlaySystem.cpp
Labels: 👍Approved
