Repository OpenEnroth/OpenEnroth, pull requests merged in 2025-04, with the labels that each got.

#1975 Fix crash due to Armageddon decoration rocks and prettify them
  src/Engine/Objects/Actor.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 👍Approved

#2001 Test for #1966 and some minor fixes
  src/Engine/Spells/CastSpellInfo.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#1978 Fix potion mixing
  src/Engine/Tables/ItemTable.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#1981 Nicer display of very large party gold amounts
  src/GUI/UI/UIGame.cpp
Labels: 👍Approved

#1982 Update instructions to deal with 'Random state desynchronized'
  HACKING.md
Labels: 👍Approved

#1984 Fix recipes sellable in magic shops
  src/Engine/Objects/Item.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#1987 Game test for enemy casting meteor showers
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#1991 Fix potions spawning in chests
  src/Engine/Objects/Item.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#2000 Replace any Spirit Lash cast by monsters with Bless
  src/Engine/Engine.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#2008 Better sugar for AccessibleVector
  test/Bin/GameTest/GameTests_1500.cpp
  test/Testing/Game/AccessibleVector.h
Labels: 👍Approved

#2007 Don't crash if we can't allocate an OpenAL source
  src/Media/Audio/OpenALSample16.cpp
Labels: ❓Questions

#2010 Fix game config changes via debug console
  resources/scripts/_definitions/def_common.lua
  resources/scripts/dev/commands/command_manager.lua
  resources/scripts/dev/commands/config_command.lua
  src/Scripting/CMakeLists.txt
  src/Scripting/ConfigBindings.cpp
  src/Scripting/ConfigBindings.h
  thirdparty/CMakeLists.txt
Labels: 👍Approved

#2011 Add test for #1808
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
  test/Testing/Game/CharacterTapeRecorder.cpp
  test/Testing/Game/CharacterTapeRecorder.h
Labels: 👍Approved

#1992 Collisions
  src/Engine/Graphics/Collisions.cpp
  src/Engine/Graphics/Indoor.cpp
  src/Engine/Graphics/Indoor.h
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_0000.cpp
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 👍Approved

#2012 Dropped raw snapshots, all snapshot code moved to Engine/Snapshots
  src/Engine/Graphics/OutdoorTerrain.cpp
  src/Engine/Graphics/OutdoorTerrain.h
  src/Engine/Objects/Character.h
  src/Engine/Snapshots/CompositeSnapshots.cpp
  src/Engine/Snapshots/CompositeSnapshots.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Snapshots/TableSerialization.cpp
  src/Engine/Tables/IconFrameTable.cpp
  src/Engine/Tables/IconFrameTable.h
  src/Engine/Time/Timer.h
  src/Library/Snapshots/CMakeLists.txt
  src/Library/Snapshots/RawSnapshots.h
  src/Library/Snapshots/SnapshotConcepts.h
  src/Media/Audio/SoundList.h
Labels: 👍Approved

#2019 Mention that we don't support CMake 4.x in HACKING
  HACKING.md
Labels: 👍Approved

#2013 Add test for #1961
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#2023 Retry flaky GH steps
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/shaders.yml
Labels: 🥺Ready for Review

#2025 Set window icon on linux
  resources/CMakeLists.txt
  resources/images/OpenEnroth.png
  src/Application/Startup/GameStarter.cpp
  src/Library/Platform/Interface/PlatformWindow.h
  src/Library/Platform/Null/NullWindow.cpp
  src/Library/Platform/Null/NullWindow.h
  src/Library/Platform/Proxy/ProxyWindow.cpp
  src/Library/Platform/Proxy/ProxyWindow.h
  src/Library/Platform/Sdl/SdlWindow.cpp
  src/Library/Platform/Sdl/SdlWindow.h
Labels: 🥺Ready for Review

#2028 HACKING - update style, drop cmake 4.x notes, spell out a better work…
  HACKING.md
Labels: 👍Approved

#2029 Add test for #1521
  src/GUI/UI/UIPopup.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 🥺Ready for Review

#2014 LUA console config list and reset, and improved set/get/toggle
  resources/scripts/_definitions/def_common.lua
  resources/scripts/dev/cheat_command_overlay.lua
  resources/scripts/dev/commands/command_manager.lua
  resources/scripts/dev/commands/config_command.lua
  resources/scripts/utils.lua
  src/Scripting/ConfigBindings.cpp
  src/Scripting/ConfigBindings.h
Labels: 👍Approved

#2020 Fix Asserts when casting Town Portal / Lloyd's from Scroll
  src/Application/Game.cpp
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/Books/LloydsBook.cpp
  src/GUI/UI/Books/LloydsBook.h
  src/GUI/UI/Books/TownPortalBook.cpp
  src/GUI/UI/Books/TownPortalBook.h
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/CMakeLists.txt
  test/Bin/GameTest/GameTests_2000.cpp
  test/Testing/Game/CommonTapeRecorder.cpp
  test/Testing/Game/CommonTapeRecorder.h
Labels: 👍Approved

#2031 Use royal griffin icon
  android/openenroth/src/main/ic_launcher-playstore.png
  resources/images/OpenEnroth.png
  src/Bin/OpenEnroth/GenerateAll.sh
  src/Bin/OpenEnroth/GenerateIcns.sh
  src/Bin/OpenEnroth/OpenEnroth.icns
  src/Bin/OpenEnroth/OpenEnroth.ico
Labels: 👍Approved

#2030 Some cleanup before merging in new Inventory
  src/Engine/Data/CMakeLists.txt
  src/Engine/Data/ChestData.h
  src/Engine/Engine.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Objects/Chest.h
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Snapshots/EntitySnapshots.cpp
  src/Engine/Snapshots/EntitySnapshots.h
  src/Engine/Snapshots/TableSerialization.cpp
  src/Engine/Snapshots/TableSerialization.h
  src/Engine/Tables/CMakeLists.txt
  src/Engine/Tables/ChestTable.cpp
  src/Engine/Tables/ChestTable.h
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIChest.cpp
  src/GUI/UI/UIChest.h
  src/GUI/UI/UIPopup.cpp
  src/Io/Mouse.cpp
  src/Io/Mouse.h
  src/Library/Geometry/Rect.h
  src/Library/Geometry/Tests/Rect_ut.cpp
  src/Library/Geometry/Vec.h
  test/Bin/GameTest/GameTests_0500.cpp
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#2034 Update flatpak icon too
  distribution/linux/io.github.openenroth.openenroth.png
Labels: 👍Approved

#2033 Update xcode & macos image
  .github/workflows/macos.yml
Labels: 👍Approved

#2038 Update to ndk28
  CMakeModules/Dependencies.cmake
  android/openenroth/build.gradle
Labels: 👍Approved

#2036 Update linux workflow to ubuntu 24.04 and gcc14
  .github/workflows/linux.yml
Labels: 👍Approved

#2039 Add test for #1974
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1500.cpp
Labels: 👍Approved

#2040 Party::setHoldingItem takes by value, add docs
  src/Engine/Evt/EvtInterpreter.cpp
  src/Engine/Graphics/Viewport.cpp
  src/Engine/Objects/Actor.cpp
  src/Engine/Objects/Character.cpp
  src/Engine/Objects/Chest.cpp
  src/Engine/Party.cpp
  src/Engine/Party.h
  src/Engine/Spells/CastSpellInfo.cpp
  src/GUI/UI/UICharacter.cpp
  src/GUI/UI/UIPopup.cpp
  src/Io/Mouse.h
Labels: 👍Approved

#2041 Fix #2017
  src/Engine/Graphics/Collisions.cpp
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_2000.cpp
Labels: 👍Approved

#2045 Game option: Show remaining power of Protection from Magic
  src/Application/GameConfig.h
  src/Engine/Localization.cpp
  src/Engine/Localization.h
  src/GUI/GUIWindow.cpp
  src/GUI/UI/UIPopup.cpp
Labels: 👍Approved

#2046 Make #1340 more easily retraceable
  test/Bin/CMakeLists.txt
  test/Bin/GameTest/GameTests_1000.cpp
Labels: 👍Approved
